# FOOD.COM DATASET PREPROCESSING AND CLEANING

2 different Food.com datasets will be used in order to achieve desired format of recipes. It is required because one of the dataset does not include ingredient units and the other one does not contain calorie information.\
Food.com - Recipes and Reviews: https://www.kaggle.com/datasets/irkaal/foodcom-recipes-and-reviews/data\
Food.com Recipes with Search Terms and Tags: https://www.kaggle.com/datasets/shuyangli94/foodcom-recipes-with-search-terms-and-tags/data\

In [1]:
import pandas as pd

In [2]:
merged_df = pd.read_parquet('mergedRecipes.parquet')

In [ ]:
#Read the first dataset
df_parquet = pd.read_parquet('recipes.parquet')

# Convert csv file to PARQUET for efficiency
csv_file_path = 'recipes_w_search_terms.csv'
df = pd.read_csv(csv_file_path)

parquet_file_path = 'recipes_w_search_terms.parquet'
df.to_parquet(parquet_file_path, engine='pyarrow')  # Use 'fastparquet' as an alternative engine if needed

df_parquet2 = pd.read_parquet('recipes_w_search_terms.parquet')

# Merge datasets on 'Name' attribute
merged_df = pd.merge(df_parquet2, df_parquet, left_on='name', right_on='Name', how='inner')

print(f"Number of matched recipes: {len(merged_df)}")

In [ ]:
# Save the merged datasest as PARQUET file
#merged_df.to_parquet('mergedRecipes.parquet', engine='pyarrow')

## Recipes

In [3]:
projectedIngr = merged_df[['Name', 'RecipeIngredientQuantities', 'RecipeIngredientParts', 'RecipeInstructions', 'ingredients_raw_str', 'Description', 'TotalTime', 'Calories', 'FatContent', 'ProteinContent', 'CarbohydrateContent','SodiumContent','SugarContent']].copy()

In [5]:
projectedIngr.rename(columns={'RecipeInstructions': 'Instructions'}, inplace=True)

In [6]:
projectedIngr.columns

Index(['Name', 'RecipeIngredientQuantities', 'RecipeIngredientParts',
       'Instructions', 'ingredients_raw_str', 'Description', 'TotalTime',
       'Calories', 'FatContent', 'ProteinContent', 'CarbohydrateContent',
       'SodiumContent', 'SugarContent'],
      dtype='object')

In [7]:
projectedIngr

,Name,RecipeIngredientQuantities,RecipeIngredientParts,Instructions,ingredients_raw_str,Description,TotalTime,Calories,FatContent,ProteinContent,CarbohydrateContent,SodiumContent,SugarContent
0,Grilled Garlic Cheese Grits,"[4, 1, 1, 4, 1 -2, 1]","[water, grits, salt, cheddar cheese, garlic, o...","[I a sauce pan, bring water to a boil; slowly ...","[""4 cups water"",""1 cup uncooked old f...","We love grits, this is another good way to ser...",PT1H5M,144.8,6.7,5.0,15.7,382.7,0.2
1,Simple Shrimp and Andouille Jambalaya,"[1, 1, 5, 1, None, None, 1, 3⁄4, 1 1⁄2, 4, 1, ...","[onion, red bell pepper, garlic cloves, large ...","[In a food processor, pulse the onion, red pep...","[""1 medium onion, chopped coarse "",""1 m...","Simple, easy and very tasty for when you are i...",PT45M,756.5,28.9,39.2,82.3,2094.9,9.7
2,black-and-white bean salad,"[1, 1, 1, 1, 1, 1, 2, 1⁄8, 1⁄8, 1 -2]","[white beans, canned black beans, tomatoes, on...","[In a large bowl, combine beans, tomato, onion...","[""1 cup canned white beans, rinsed and dra...",Make and share this black-and-white bean salad...,PT5M,159.0,1.6,9.1,28.3,318.3,2.1
3,Crock Pot Italian Zucchini,"[2, 2, 2 -3, 1, 4, 1, 2, 1, None]","[zucchini, diced tomatoes, onion, garlic, gree...",[Put all ingredients in the crock pot and cook...,"[""2 zucchini, sliced "",""2 small yel...",Make and share this Crock Pot Italian Zucchini...,PT6H10M,47.1,0.4,2.6,10.4,19.1,4.6
4,Crock Pot Italian Zucchini,"[3, 1 1⁄2, 3, 1⁄4, 2]","[zucchini, onions, diced tomatoes, sugar]",[Spray a slow cooker container with olive oil-...,"[""2 zucchini, sliced "",""2 small yel...",Make and share this Crock Pot Italian Zucchini...,PT4H15M,87.5,3.2,2.0,14.4,110.8,10.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1601848,Blackberry Orange Scones,"[2 1⁄2, 2, 6, 1⁄4, 1, 2, 1, 3⁄4, 1⁄4]","[unbleached flour, baking soda, butter, orange...",[Sift about 2 cups of flour onto a piece of wa...,"[""2 1/2 cups unbleached flour"",""2 teaspo...",Make and share this Blackberry Orange Scones r...,PT27M,244.8,9.1,5.1,35.4,390.5,3.9
1601849,Slow Cooker Garlic Chicken With Rosemary,"[1, 2, 3, 1⁄2, 1⁄2, 1⁄2, 12, 2, 3]","[roasting chickens, lemons, rosemary sprigs, p...","[Place rosemary springs, 1 lemon half, celery,...","[""1 (5 lb) roasting chickens, rinsed and ...",Make and share this Slow Cooker Garlic Chicken...,PT7H20M,566.2,38.9,43.2,9.3,379.4,3.0
1601850,Pot Roast with Port (Stove Top),"[2 -3, 2, 1, 1, 2, 2, 1⁄2, 3, None, None]","[boneless beef chuck roast, olive oil, flour, ...","[In a large pan, heat oil and brown roast on b...","[""2 -3 lbs boneless beef chuck roast"",""2 ...",This is a recipe from the Frugal Gourmet cooki...,PT1H55M,828.2,57.1,46.9,14.6,503.3,5.6
1601851,Kapusta ( Cabbage and Kielbasa ),"[8, 3, 2, 3, 1.5, 8, 1⁄4, 1, None]","[cabbage, cabbage, kielbasa, onions, water, ba...",[Saute bacon in large pan until browned. Leav...,"[""8 cups cabbage or 2 heads cabbage,...",Make and share this Kapusta ( Cabbage and Kiel...,PT2H,688.0,48.5,25.6,39.2,2078.8,19.2
1601852,Yellow or Zucchini Squash Pie,"[4, 1, 1⁄2 - 1, 1, 1, None, 2, 2, 1, 1]","[zucchini, onion, butter, oregano, basil, eggs...","[Melt butter in skillet. Add squash, onions, s...","[""4 cups zucchini (can mix the squash if ...",This recipe was given to my mom from a lady wh...,PT40M,411.0,28.1,15.4,25.1,602.4,5.0

### Fix total time

In [8]:
import re

def convert_to_minutes(duration):
    match = re.match(r'PT(?:(\d+)H)?(\d+)M', duration)
    if match:
        hours = int(match.group(1)) if match.group(1) else 0
        minutes = int(match.group(2))
        # Convert hours to minutes and add the minutes
        total_minutes = hours * 60 + minutes
        return total_minutes
    else:
        return None

In [9]:
projectedIngr['TotalTime'] = projectedIngr['TotalTime'].apply(convert_to_minutes)

In [10]:
projectedIngr.head()

,Name,RecipeIngredientQuantities,RecipeIngredientParts,Instructions,ingredients_raw_str,Description,TotalTime,Calories,FatContent,ProteinContent,CarbohydrateContent,SodiumContent,SugarContent
0,Grilled Garlic Cheese Grits,"[4, 1, 1, 4, 1 -2, 1]","[water, grits, salt, cheddar cheese, garlic, o...","[I a sauce pan, bring water to a boil; slowly ...","[""4 cups water"",""1 cup uncooked old f...","We love grits, this is another good way to ser...",65.0,144.8,6.7,5.0,15.7,382.7,0.2
1,Simple Shrimp and Andouille Jambalaya,"[1, 1, 5, 1, None, None, 1, 3⁄4, 1 1⁄2, 4, 1, ...","[onion, red bell pepper, garlic cloves, large ...","[In a food processor, pulse the onion, red pep...","[""1 medium onion, chopped coarse "",""1 m...","Simple, easy and very tasty for when you are i...",45.0,756.5,28.9,39.2,82.3,2094.9,9.7
2,black-and-white bean salad,"[1, 1, 1, 1, 1, 1, 2, 1⁄8, 1⁄8, 1 -2]","[white beans, canned black beans, tomatoes, on...","[In a large bowl, combine beans, tomato, onion...","[""1 cup canned white beans, rinsed and dra...",Make and share this black-and-white bean salad...,5.0,159.0,1.6,9.1,28.3,318.3,2.1
3,Crock Pot Italian Zucchini,"[2, 2, 2 -3, 1, 4, 1, 2, 1, None]","[zucchini, diced tomatoes, onion, garlic, gree...",[Put all ingredients in the crock pot and cook...,"[""2 zucchini, sliced "",""2 small yel...",Make and share this Crock Pot Italian Zucchini...,370.0,47.1,0.4,2.6,10.4,19.1,4.6
4,Crock Pot Italian Zucchini,"[3, 1 1⁄2, 3, 1⁄4, 2]","[zucchini, onions, diced tomatoes, sugar]",[Spray a slow cooker container with olive oil-...,"[""2 zucchini, sliced "",""2 small yel...",Make and share this Crock Pot Italian Zucchini...,255.0,87.5,3.2,2.0,14.4,110.8,10.6

### Fix Quantities

In [87]:
import re
from fractions import Fraction

def fix_quantities(quantities):
    cleaned_quantities = []
    for q in quantities:
        if q is None:
            return None
    
        if isinstance(q, str):

            q = q.replace('⁄', '/') #Replace Unicode character '⁄' (U+2044) with the regular slash '/'
            #print(q)

            # Handle ranges with mixed fractions and/or integers (e.g., '1 - 1 1/2', '1/3 - 1/2', '1/2 - 1')
            if re.match(r'(\d+/\d+|\d+\s+\d+/\d+|\d+)\s*-\s*(\d+/\d+|\d+\s+\d+/\d+|\d+)', q):
                parts = re.split(r'\s*-\s*', q)  # Split on the dash, accounting for possible spaces
                
                # Process part1, check if it's a mixed fraction, pure fraction, or integer
                if re.match(r'\d+\s+\d+/\d+', parts[0]):  # Mixed fraction
                    part1_whole, part1_frac = parts[0].split()
                    part1 = float(part1_whole) + float(Fraction(part1_frac))
                elif '/' in parts[0]:  # Pure fraction
                    part1 = float(Fraction(parts[0]))
                else:  # Integer
                    part1 = float(parts[0])

                # Process part2, same checks as part1
                if re.match(r'\d+\s+\d+/\d+', parts[1]):  # Mixed fraction
                    part2_whole, part2_frac = parts[1].split()
                    part2 = float(part2_whole) + float(Fraction(part2_frac))
                elif '/' in parts[1]:  # Pure fraction
                    part2 = float(Fraction(parts[1]))
                else:  # Integer
                    part2 = float(parts[1])

                # Get the minimum value of the two parts
                min_value = min(part1, part2)
                cleaned_quantities.append(min_value)

            # Handle mixed fractions (e.g., '1 1/2')
            elif re.match(r'\d+\s+\d+/\d+', q):
                parts = q.split()  # Split the whole number and the fraction
                whole_number = float(parts[0])  # Convert the whole number part
                fraction_part = float(Fraction(parts[1]))  # Convert the fraction part
                decimal_value = whole_number + fraction_part  # Sum both parts
                cleaned_quantities.append(decimal_value)

            # Handle pure fractions (e.g., '1/2')
            elif re.match(r'\d+/\d+', q):
                decimal_value = float(Fraction(q))  # Convert the fraction directly to decimal
                cleaned_quantities.append(decimal_value)

            else:
                cleaned_quantities.append(q)  # Leave other string values unchanged
        else:
            cleaned_quantities.append(q)  # Leave non-string values unchanged

    return cleaned_quantities

In [ ]:
# Apply the cleaning function to the quantity column
projectedIngr['Quantities'] = projectedIngr['RecipeIngredientQuantities'].apply(fix_quantities)
#projectedIngr['Instructions'] = projectedIngr['Instructions'].apply(fix_quantities)

projectedIngr.drop(columns=['RecipeIngredientQuantities'], inplace=True)

projectedIngr.head()

In [59]:
projectedIngr.head()

,Name,RecipeIngredientParts,Instructions,Description,TotalTime,Calories,FatContent,ProteinContent,CarbohydrateContent,Quantities,Unit
0,Grilled Garlic Cheese Grits,"[water, grits, salt, cheddar cheese, garlic, o...","[I a sauce pan, bring water to a boil; slowly ...","We love grits, this is another good way to ser...",65.0,144.8,6.7,5.0,15.7,"[4, 1, 1, 4, 1.0, 1]","[cups, cup, teaspoon, ounces, clove, tablespoon]"
1,Simple Shrimp and Andouille Jambalaya,"[onion, red bell pepper, garlic cloves, large ...","[In a food processor, pulse the onion, red pep...","Simple, easy and very tasty for when you are i...",45.0,756.5,28.9,39.2,82.3,"[1, 1, 5, 1, None, None, 1, 0.75, 1.5, 4, 1, 2...","[none, none, cloves, lb, none, none, tablespoo..."
2,black-and-white bean salad,"[white beans, canned black beans, tomatoes, on...","[In a large bowl, combine beans, tomato, onion...",Make and share this black-and-white bean salad...,5.0,159.0,1.6,9.1,28.3,"[1, 1, 1, 1, 1, 1, 2, 0.125, 0.125, 1.0]","[cup, cup, none, none, stalk, tablespoon, tabl..."
3,Crock Pot Italian Zucchini,"[zucchini, diced tomatoes, onion, garlic, gree...",[Put all ingredients in the crock pot and cook...,Make and share this Crock Pot Italian Zucchini...,370.0,47.1,0.4,2.6,10.4,"[2, 2, 2.0, 1, 4, 1, 2, 1, None]","[none, none, cans, none, cloves, none, teaspoo..."
4,Crock Pot Italian Zucchini,"[zucchini, onions, diced tomatoes, sugar]",[Spray a slow cooker container with olive oil-...,Make and share this Crock Pot Italian Zucchini...,255.0,87.5,3.2,2.0,14.4,"[3, 1.5, 3, 0.25, 2]","[none, none, cans, none, cloves, none, teaspoo..."

### Generate Unit Column

In [13]:
units_list = [
    'teaspoon', 'teaspoons', 'tsp',
    'tablespoon', 'tablespoons', 'tbsp',
    'cup', 'cups',
    'pint', 'pints',
    'quart', 'quarts',
    'gallon', 'gallons',
    'ounce', 'ounces', 'oz',
    'pound', 'pounds', 'lb', 'lbs',
    'gram', 'grams', 'g',
    'kilogram', 'kilograms', 'kg',
    'liter', 'liters', 'l',
    'milliliter', 'milliliters', 'ml',
    'package', 'packages',
    'can', 'cans',
    'slice', 'slices',
    'clove', 'cloves',
    'stick', 'sticks',
    'sprig', 'sprigs',
    'bunch', 'bunches',
    'pinch', 'pinches',
    'dash', 'dashes',
    'head', 'heads',
    'stalk', 'stalks',
    'piece', 'pieces',
    'jar', 'jars',
    'bottle', 'bottles',
    'bag', 'bags',
    'box', 'boxes',
    'block', 'blocks',
    'packet', 'packets',
    'envelope', 'envelopes',
    'sheet', 'sheets',
    'square', 'squares',
    'strip', 'strips',
    'drop', 'drops',
    'fillet', 'fillets',
    'inch', 'inches'
]

In [14]:
# Create a regex pattern to match any unit from the list
units_pattern = r'\b(?:' + '|'.join(units_list) + r')\b'

In [15]:
import ast  # To safely convert string representation of lists to actual lists

# Function to extract units from the ingredient string
def extract_units(ingredient_list_str):
    ingredient_list = ast.literal_eval(ingredient_list_str)  # Convert string to list
    units = []
    for ingredient in ingredient_list:
        match = re.search(units_pattern, ingredient, re.IGNORECASE)  # Case-insensitive search
        if match:
            units.append(match.group(0).lower())  # Store unit in lowercase for consistency
        else:
            units.append('none')  # Assign 'none' if no unit found
    return units

In [16]:
# Apply the function to extract units and create a new 'Unit' column
projectedIngr['Unit'] = projectedIngr['ingredients_raw_str'].apply(extract_units)

In [ ]:
projectedIngr.drop(columns=['SodiumContent', 'SugarContent'], inplace=True)

In [21]:
projectedIngr.drop(columns=['ingredients_raw_str'], inplace=True)

In [22]:
projectedIngr.head()

,Name,RecipeIngredientParts,Instructions,Description,TotalTime,Calories,FatContent,ProteinContent,CarbohydrateContent,Quantities,Unit
0,Grilled Garlic Cheese Grits,"[water, grits, salt, cheddar cheese, garlic, o...","[I a sauce pan, bring water to a boil; slowly ...","We love grits, this is another good way to ser...",65.0,144.8,6.7,5.0,15.7,"[4, 1, 1, 4, 1.0, 1]","[cups, cup, teaspoon, ounces, clove, tablespoon]"
1,Simple Shrimp and Andouille Jambalaya,"[onion, red bell pepper, garlic cloves, large ...","[In a food processor, pulse the onion, red pep...","Simple, easy and very tasty for when you are i...",45.0,756.5,28.9,39.2,82.3,"[1, 1, 5, 1, None, None, 1, 0.75, 1.5, 4, 1, 2...","[none, none, cloves, lb, none, none, tablespoo..."
2,black-and-white bean salad,"[white beans, canned black beans, tomatoes, on...","[In a large bowl, combine beans, tomato, onion...",Make and share this black-and-white bean salad...,5.0,159.0,1.6,9.1,28.3,"[1, 1, 1, 1, 1, 1, 2, 0.125, 0.125, 1.0]","[cup, cup, none, none, stalk, tablespoon, tabl..."
3,Crock Pot Italian Zucchini,"[zucchini, diced tomatoes, onion, garlic, gree...",[Put all ingredients in the crock pot and cook...,Make and share this Crock Pot Italian Zucchini...,370.0,47.1,0.4,2.6,10.4,"[2, 2, 2.0, 1, 4, 1, 2, 1, None]","[none, none, cans, none, cloves, none, teaspoo..."
4,Crock Pot Italian Zucchini,"[zucchini, onions, diced tomatoes, sugar]",[Spray a slow cooker container with olive oil-...,Make and share this Crock Pot Italian Zucchini...,255.0,87.5,3.2,2.0,14.4,"[3, 1.5, 3, 0.25, 2]","[none, none, cans, none, cloves, none, teaspoo..."

## Formatting

In [117]:
import numpy as np

# Helper function to convert values to JSON-serializable types
def to_serializable(value):
    if isinstance(value, np.ndarray):
        return value.tolist()  # Convert ndarray to a Python list
    elif isinstance(value, (np.integer, np.floating)):
        return float(value)  # Convert numpy numbers to native floats
    elif isinstance(value, list):
        return [to_serializable(v) for v in value]  # Recursively convert lists
    elif value in [None, 'none', '', 'null']:  # Treat 'none' or missing as None
        return None
    return value  # Return the value as-is for other types

In [118]:
# Formatted instructions as a single string rather than a string 
def format_instructions(instructions):
    return ' '.join([f"{i + 1}. {step}" for i, step in enumerate(instructions)])

In [119]:
# Updated recipe conversion function
def recipe_to_dict(row):
    ingredients = [
        {
            "name": to_serializable(name),
            "quantity": to_serializable(qty),
            "unit": to_serializable(unit) if unit != 'none' else None
        }
        for name, qty, unit in zip(row['RecipeIngredientParts'], row['Quantities'], row['Unit'])
    ]

    # Build the recipe dictionary
    recipe = {
        "name": to_serializable(row["Name"]),
        "instructions": to_serializable(format_instructions(row["Instructions"])),
        "ingredients": ingredients,
        "total_time": to_serializable(row["TotalTime"]),
        "calories": to_serializable(row["Calories"]),
        "fat": to_serializable(row["FatContent"]),
        "protein": to_serializable(row["ProteinContent"]),
        "carbohydrate": to_serializable(row["CarbohydrateContent"]),
        "desc": row["Description"]
    }

    return recipe

In [120]:
import json

recipes = [recipe_to_dict(row) for _, row in projectedIngr.iterrows()]

# Convert to JSON and replace 'null' with 'None'
recipes_json = json.dumps(recipes, indent=4)
recipes_json = recipes_json.replace("null", "\"None\"")

# Save the JSON output to a file
with open("outputRecipes.json", "w") as f:
    f.write(recipes_json)

print("JSON file saved successfully as 'recipes.json'")

JSON file saved successfully as 'recipes.json'

In [103]:
##############################
### TO DETECT MISSIN UNITS ###
##############################

# def detect_missing_units_and_save(ingredient_list_str, output_file='missing_units.txt'):
#     ingredient_list = ast.literal_eval(ingredient_list_str)  # Convert string to list
#     missing_units = []  # Store ingredients with no detected unit

#     for ingredient in ingredient_list:
#         match = re.search(units_pattern, ingredient, re.IGNORECASE)  # Case-insensitive search
#         if not match:  # If no unit found, log it
#             missing_units.append(ingredient)

#     # Write missing units to the specified text file
#     if missing_units:
#         with open(output_file, 'a') as f:  # Open in append mode to add entries
#             f.write("Ingredients with missing units:\n")
#             for ingr in missing_units:
#                 f.write(f"- {ingr}\n")
#             f.write("\n")  # Add a new line for separation

# projectedIngr['ingredients_raw_str'].apply(lambda x: detect_missing_units_and_save(x))