In [1]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.exc import OperationalError
import ast

### read parquet

In [2]:
parquet_file = "recipes.parquet"
#chunks = pd.read_parquet(parquet_file, engine="pyarrow", chunksize=chunk_size)
df = pd.read_parquet(parquet_file, engine="pyarrow")

In [3]:
df

,ID,Name,Instructions,Ingredients,Total Time,Calories,Fat,Protein,Carbohydrate,Label,Category
0,0,"Lentil, Apple, and Turkey Wrap","1. Place the stock, lentils, celery, carrot, t...","[{'name': 'vegetable or chicken stock', 'quant...",30.0,426.0,7.0,30.0,NaN,vegetarian,garlish
1,1,Boudin Blanc Terrine with Red Onion Confit,Combine first 9 ingredients in heavy saucepan...,"[{'name': 'whipping cream', 'quantity': 5.5, '...",177.0,403.0,23.0,18.0,NaN,meat,main dish
2,4,Spinach Noodle Casserole,Preheat oven to 350°F. Lightly grease 8x8x2-in...,"[{'name': 'spinach souffle', 'quantity': 1.0, ...",55.0,547.0,32.0,20.0,NaN,vegetarian,main dish
3,5,The Best Blts,"Mix basil, mayonnaise and butter in processor ...","[{'name': 'basil leaves', 'quantity': 10.5, 'u...",8.0,948.0,79.0,19.0,NaN,meat,main dish
4,6,Ham and Spring Vegetable Salad with Shallot Vi...,Cook potatoes and carrots in pot of boiling s...,"[{'name': 'red-skinned potatoes', 'quantity': ...",10.0,NaN,NaN,NaN,NaN,meat,main dish
...,...,...,...,...,...,...,...,...,...,...,...
1071004,1174475,Maple Apple Baked Beans,1. Place beans in soup kettle; add water to co...,"[{'name': 'navy beans', 'quantity': 91, 'unit'...",375.0,518.1,19.0,17.3,72.3,meat,garlish
1071005,1174476,Blackberry Orange Scones,1. Sift about 2 cups of flour onto a piece of ...,"[{'name': 'flour', 'quantity': 91, 'unit': 'cu...",27.0,244.8,9.1,5.1,35.4,"pescetarian, vegetarian",dessert
1071006,1174477,Slow Cooker Garlic Chicken With Rosemary,"1. Place rosemary springs, 1 lemon half, celer...","[{'name': 'roasting chickens', 'quantity': 91,...",440.0,566.2,38.9,43.2,9.3,meat,main dish
1071007,1174478,Kapusta ( Cabbage and Kielbasa ),1. Saute bacon in large pan until browned. Le...,"[{'name': 'cabbage', 'quantity': 91, 'unit': '...",NaN,688.0,48.5,25.6,39.2,meat,main dish
1071008,1174479,Yellow or Zucchini Squash Pie,"1. Melt butter in skillet. Add squash, onions,...","[{'name': 'zucchini', 'quantity': 91, 'unit': ...",40.0,411.0,28.1,15.4,25.1,vegetarian,garlish

In [4]:
df.columns

Index(['ID', 'Name', 'Instructions', 'Ingredients', 'Total Time', 'Calories',
       'Fat', 'Protein', 'Carbohydrate', 'Label', 'Category'],
      dtype='object')

In [5]:
df_upload_recipe = df

### database connection

In [6]:
from sqlalchemy import create_engine, text

# Replace these with actual values
DB_HOST = "frs-db.ch88c4s48jz3.eu-north-1.rds.amazonaws.com"
DB_NAME = "FRS"
DB_USER = "postgres"
DB_PASSWORD = "DefinedAtTheDisco01*"  
DB_PORT = "5432" 

# Create a database connection
engine = create_engine(f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}")

try:
    with engine.connect() as connection:
        result = connection.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'"))
        tables = [row[0] for row in result.fetchall()]
        
        print("✅ Connected to the database successfully!")
        print("Available tables:", tables)

except Exception as e:
    print("❌ Failed to connect to the database.")
    print("Error:", e)

✅ Connected to the database successfully!
Available tables: ['recipe_ingr', 'category', 'recipe', 'pref_recipe', 'preference', 'liked_recipes', 'users', 'saved_recipes', 'user_pref', 'allergy', 'ingredient']

## uplaod tables

In [7]:
chunk_size = 50000

In [8]:
def upload_table(df_to_upload, table):
    try:
        # 🔹 Insert data in chunks with proper rollback handling
        for i in range(0, len(df_to_upload), chunk_size):
            try:
                with engine.begin() as connection:  # Ensures transactions are handled safely
                    df_to_upload.iloc[i:i+chunk_size].to_sql(table, connection, if_exists="append", index=False)
                    print(f"Uploaded {i+chunk_size}/{len(df_to_upload)} rows")

            except OperationalError as e:
                print(f"Connection lost during batch {i}-{i+chunk_size}, retrying...")
                continue  # Retry the next batch

        print("Full recipe dataset uploaded successfully!")

    except Exception as e:
        print("Fatal error uploading data:", e)

### recipe (without category)

In [ ]:
# 🔹 Mapping DataFrame columns to Database Table columns
column_mapping = {
    "ID": "recipe_id",
    "Name": "recipe_name",
    "Instructions": "instruction",
    "Ingredients": "ingredient",  
    "Total Time": "total_time",
    "Calories": "calories",
    "Fat": "fat",
    "Protein": "protein",
    "Carbohydrate": "carb",
}

In [ ]:
df_upload_recipe = df_upload_recipe.rename(columns=column_mapping)
df_upload_recipe = df_upload_recipe[list(column_mapping.values())] # Select only the mapped columns

In [ ]:
df_upload_recipe.columns

Index(['recipe_id', 'recipe_name', 'instruction', 'ingredient', 'total_time',
       'calories', 'fat', 'protein', 'carb'],
      dtype='object')

In [ ]:
try:
    # 🔹 Insert data in chunks with proper rollback handling
    for i in range(0, len(df_upload_recipe), chunk_size):
        try:
            with engine.begin() as connection:  # Ensures transactions are handled safely
                df_upload_recipe.iloc[i:i+chunk_size].to_sql("recipe", connection, if_exists="append", index=False)
                print(f"Uploaded {i+chunk_size}/{len(df_upload_recipe)} rows")

        except OperationalError as e:
            print(f"Connection lost during batch {i}-{i+chunk_size}, retrying...")
            continue  # Retry the next batch

    print("Full recipe dataset uploaded successfully!")

except Exception as e:
    print("Fatal error uploading data:", e)

✅ Uploaded 50000/1071009 rows
✅ Uploaded 100000/1071009 rows
✅ Uploaded 150000/1071009 rows
✅ Uploaded 200000/1071009 rows
✅ Uploaded 250000/1071009 rows
✅ Uploaded 300000/1071009 rows
✅ Uploaded 350000/1071009 rows
✅ Uploaded 400000/1071009 rows
✅ Uploaded 450000/1071009 rows
✅ Uploaded 500000/1071009 rows
✅ Uploaded 550000/1071009 rows
✅ Uploaded 600000/1071009 rows
✅ Uploaded 650000/1071009 rows
✅ Uploaded 700000/1071009 rows
✅ Uploaded 750000/1071009 rows
✅ Uploaded 800000/1071009 rows
✅ Uploaded 850000/1071009 rows
✅ Uploaded 900000/1071009 rows
✅ Uploaded 950000/1071009 rows
✅ Uploaded 1000000/1071009 rows
✅ Uploaded 1050000/1071009 rows
✅ Uploaded 1100000/1071009 rows
🚀 Full recipe dataset uploaded successfully!

### ingredient

In [ ]:
df.columns

Index(['ID', 'Name', 'Instructions', 'Ingredients', 'Total Time', 'Calories',
       'Fat', 'Protein', 'Carbohydrate', 'Label', 'Category'],
      dtype='object')

In [ ]:
# 🔹 Extract ingredient names from the list
ingredient_set = set()  # To store unique ingredient names

for ingredients in df["Ingredients"].dropna():  # Ignore missing values
    ingredient_list = ast.literal_eval(ingredients)  # Convert string to list
    for item in ingredient_list:
        ingredient_name = item["name"].strip().replace("'", "''")  # Escape apostrophes
        ingredient_set.add(ingredient_name)

# 🔹 Convert to DataFrame
ingredient_df = pd.DataFrame({"ingr_name": list(ingredient_set)})

In [ ]:
ingredient_df

                                                ingr_name
0                                       canfruit cocktail
1                                    red cinnamon candies
2                              good quality matcha powder
3                                  millet or white quinoa
4                                      brown sugar-packed
...                                                   ...
186896                                  pizza dough yeast
186897                     cauliflower or broccoli floret
186898          vegetable stock or chicken stock or broth
186899                 instant mint-chocolate pudding mix
186900  apricot preserve or raspberry preserve or pres...

[186901 rows x 1 columns]

In [ ]:
try:
    # 🔹 Insert ingredients in chunks
    for i in range(0, len(ingredient_df), chunk_size):
        ingredient_df.iloc[i:i+chunk_size].to_sql("ingredient", engine, if_exists="append", index=False)
        print(f"Uploaded {i+chunk_size}/{len(ingredient_df)} ingredients")

    print("Successfully uploaded all unique ingredients!")

except Exception as e:
    print("Error uploading ingredients:", e)

Uploaded 50000/186901 ingredients
Uploaded 100000/186901 ingredients
Uploaded 150000/186901 ingredients
Uploaded 200000/186901 ingredients
Successfully uploaded all unique ingredients!

### category

In [ ]:
df_upload_recipe = df

In [ ]:
# 🔹 Mapping DataFrame columns to Database Table columns
column_mapping = {
    "Category": "cat_name"
}

df_upload_recipe = df_upload_recipe.rename(columns=column_mapping)
df_upload_recipe = df_upload_recipe[list(column_mapping.values())] # Select only the mapped columns

In [ ]:
df_upload_recipe

          cat_name
0          garlish
1        main dish
2        main dish
3        main dish
4        main dish
...            ...
1071004    garlish
1071005    dessert
1071006  main dish
1071007  main dish
1071008    garlish

[1071009 rows x 1 columns]

In [ ]:
unique_categories = df_upload_recipe['cat_name'].dropna().unique()
print(unique_categories)

['garlish' 'main dish' 'dessert' 'appetizer' 'beverage' 'soup' 'breakfast'
 'bread']

In [ ]:
df_upload_recipe = pd.DataFrame({"cat_name": unique_categories})

In [ ]:
df_upload_recipe

    cat_name
0    garlish
1  main dish
2    dessert
3  appetizer
4   beverage
5       soup
6  breakfast
7      bread

In [ ]:
category_data = [
    (0, "garlish"),
    (1, "main dish"),
    (2, "dessert"),
    (3, "appetizer"),
    (4, "beverage"),
    (5, "soup"),
    (6, "breakfast"),
    (7, "bread")
]

# 🔹 Convert to DataFrame
category_df = pd.DataFrame(category_data, columns=["category_id", "cat_name"])

In [ ]:
category_df

   category_id   cat_name
0            0    garlish
1            1  main dish
2            2    dessert
3            3  appetizer
4            4   beverage
5            5       soup
6            6  breakfast
7            7      bread

In [ ]:
upload_table(category_df, "category")

Connection lost during batch 0-50000, retrying...
Full recipe dataset uploaded successfully!

### pref

In [ ]:
df.columns

Index(['ID', 'Name', 'Instructions', 'Ingredients', 'Total Time', 'Calories',
       'Fat', 'Protein', 'Carbohydrate', 'Label', 'Category'],
      dtype='object')

In [ ]:
df_upload_recipe = df

In [ ]:
# 🔹 Mapping DataFrame columns to Database Table columns
column_mapping = {
    "Label": "pref_name"
}

df_upload_recipe = df_upload_recipe.rename(columns=column_mapping)
df_upload_recipe = df_upload_recipe[list(column_mapping.values())] # Select only the mapped columns

In [ ]:
unique_categories = df_upload_recipe['pref_name'].dropna().unique()
print(unique_categories)

['vegetarian' 'meat' 'dairy-free, gluten-free, pescetarian, vegetarian'
 'pescetarian' 'pescetarian, vegetarian'
 'dairy-free, gluten-free, pescetarian, vegan, vegetarian'
 'gluten-free, vegetarian' 'dairy-free, gluten-free, pescetarian']

In [ ]:
df_upload_recipe = pd.DataFrame({"pref_name": unique_categories})

In [ ]:
['vegetarian' 'meat' 'dairy-free, gluten-free, pescetarian, vegetarian'
 'pescetarian' 'pescetarian, vegetarian'
 'dairy-free, gluten-free, pescetarian, vegan, vegetarian'
 'gluten-free, vegetarian' 'dairy-free, gluten-free, pescetarian']

['vegetarianmeatdairy-free, gluten-free, pescetarian, vegetarianpescetarianpescetarian, vegetariandairy-free, gluten-free, pescetarian, vegan, vegetariangluten-free, vegetariandairy-free, gluten-free, pescetarian']

In [ ]:
label_data = [
    (0, "vegetarian"),
    (1, "meat"),
    (2, "dairy-free"),
    (3, "pescetarian"),
    (4, "gluten-free"),
    (5, "vegan"),
]

# 🔹 Convert to DataFrame
label_df = pd.DataFrame(label_data, columns=["pref_id", "pref_name"])

In [ ]:
label_df

   pref_id    pref_name
0        0   vegetarian
1        1         meat
2        2   dairy-free
3        3  pescetarian
4        4  gluten-free
5        5        vegan

In [ ]:
upload_table(label_df, "preference")

Uploaded 50000/6 rows
Full recipe dataset uploaded successfully!

### pref_recipe

In [ ]:
df

,ID,Name,Instructions,Ingredients,Total Time,Calories,Fat,Protein,Carbohydrate,Label,Category
0,0,"Lentil, Apple, and Turkey Wrap","1. Place the stock, lentils, celery, carrot, t...","[{'name': 'vegetable or chicken stock', 'quant...",30.0,426.0,7.0,30.0,NaN,vegetarian,garlish
1,1,Boudin Blanc Terrine with Red Onion Confit,Combine first 9 ingredients in heavy saucepan...,"[{'name': 'whipping cream', 'quantity': 5.5, '...",177.0,403.0,23.0,18.0,NaN,meat,main dish
2,4,Spinach Noodle Casserole,Preheat oven to 350°F. Lightly grease 8x8x2-in...,"[{'name': 'spinach souffle', 'quantity': 1.0, ...",55.0,547.0,32.0,20.0,NaN,vegetarian,main dish
3,5,The Best Blts,"Mix basil, mayonnaise and butter in processor ...","[{'name': 'basil leaves', 'quantity': 10.5, 'u...",8.0,948.0,79.0,19.0,NaN,meat,main dish
4,6,Ham and Spring Vegetable Salad with Shallot Vi...,Cook potatoes and carrots in pot of boiling s...,"[{'name': 'red-skinned potatoes', 'quantity': ...",10.0,NaN,NaN,NaN,NaN,meat,main dish
...,...,...,...,...,...,...,...,...,...,...,...
1071004,1174475,Maple Apple Baked Beans,1. Place beans in soup kettle; add water to co...,"[{'name': 'navy beans', 'quantity': 91, 'unit'...",375.0,518.1,19.0,17.3,72.3,meat,garlish
1071005,1174476,Blackberry Orange Scones,1. Sift about 2 cups of flour onto a piece of ...,"[{'name': 'flour', 'quantity': 91, 'unit': 'cu...",27.0,244.8,9.1,5.1,35.4,"pescetarian, vegetarian",dessert
1071006,1174477,Slow Cooker Garlic Chicken With Rosemary,"1. Place rosemary springs, 1 lemon half, celer...","[{'name': 'roasting chickens', 'quantity': 91,...",440.0,566.2,38.9,43.2,9.3,meat,main dish
1071007,1174478,Kapusta ( Cabbage and Kielbasa ),1. Saute bacon in large pan until browned. Le...,"[{'name': 'cabbage', 'quantity': 91, 'unit': '...",NaN,688.0,48.5,25.6,39.2,meat,main dish
1071008,1174479,Yellow or Zucchini Squash Pie,"1. Melt butter in skillet. Add squash, onions,...","[{'name': 'zucchini', 'quantity': 91, 'unit': ...",40.0,411.0,28.1,15.4,25.1,vegetarian,garlish

In [ ]:
label_data = [
    (0, "vegetarian"),
    (1, "meat"),
    (2, "dairy-free"),
    (3, "pescetarian"),
    (4, "gluten-free"),
    (5, "vegan"),
]

In [ ]:
def generate_pref_recipe(df, label_data):
    # Convert label_data into a dictionary {label_name: pref_id}
    label_map = {label: pref_id for pref_id, label in label_data}
    #print(label_map)
    pref_recipe_data = []
    
    # Iterate through each recipe
    for _, row in df.iterrows():
        recipe_id = row["ID"]
        labels = row["Label"]
        
        if pd.isna(labels):  # Handle missing labels
            continue

        labels = labels.split(",")  # Split multi-label strings
        #print(labels)
        # Map labels to pref_id
        for label in labels:
            label = label.strip()  # Remove spaces
            if label in label_map:
                pref_recipe_data.append((recipe_id, label_map[label]))

    return pref_recipe_data

In [ ]:
pref_recipe = generate_pref_recipe(df, label_data)
#print(pref_recipe)

KeyboardInterrupt:

In [ ]:
pref_recipe

[(0, 0),
 (1, 1),
 (4, 0),
 (5, 1),
 (6, 1),
 (7, 0),
 (9, 1),
 (10, 1),
 (11, 1),
 (13, 1),
 (14, 2),
 (14, 4),
 (14, 3),
 (14, 0),
 (15, 3),
 (16, 0),
 (17, 1),
 (18, 3),
 (19, 1),
 (21, 1),
 (22, 3),
 (24, 3),
 (25, 0),
 (26, 0),
 (27, 2),
 (27, 4),
 (27, 3),
 (27, 0),
 (28, 3),
 (28, 0),
 (29, 3),
 (29, 0),
 (30, 3),
 (30, 0),
 (31, 2),
 (31, 4),
 (31, 3),
 (31, 5),
 (31, 0),
 (33, 1),
 (34, 0),
 (35, 1),
 (36, 3),
 (36, 0),
 (37, 2),
 (37, 4),
 (37, 3),
 (37, 5),
 (37, 0),
 (38, 3),
 (40, 0),
 (41, 3),
 (42, 3),
 (42, 0),
 (43, 3),
 (44, 1),
 (45, 2),
 (45, 4),
 (45, 3),
 (45, 5),
 (45, 0),
 (46, 1),
 (47, 1),
 (48, 0),
 (49, 2),
 (49, 4),
 (49, 3),
 (49, 0),
 (50, 1),
 (51, 0),
 (54, 0),
 (55, 1),
 (56, 1),
 (57, 0),
 (58, 3),
 (58, 0),
 (59, 0),
 (60, 0),
 (61, 1),
 (62, 0),
 (63, 0),
 (64, 0),
 (65, 0),
 (66, 3),
 (66, 0),
 (68, 0),
 (69, 1),
 (70, 0),
 (71, 1),
 (72, 0),
 (73, 2),
 (73, 4),
 (73, 3),
 (73, 0),
 (74, 0),
 (75, 0),
 (76, 2),
 (76, 4),
 (76, 3),
 (76, 5),
 (76, 0),
 (77, 4),
 (77, 0),
 (78, 0),
 (79, 0),
 (80, 1),
 (81, 0),
 (83, 4),
 (83, 0),
 (85, 1),
 (86, 1),
 (87, 1),
 (88, 1),
 (90, 4),
 (90, 0),
 (91, 3),
 (92, 1),
 (93, 0),
 (94, 1),
 (95, 2),
 (95, 4),
 (95, 3),
 (95, 5),
 (95, 0),
 (96, 2),
 (96, 4),
 (96, 3),
 (96, 0),
 (97, 1),
 (98, 2),
 (98, 4),
 (98, 3),
 (98, 0),
 (99, 2),
 (99, 4),
 (99, 3),
 (99, 5),
 (99, 0),
 (100, 3),
 (105, 0),
 (106, 2),
 (106, 4),
 (106, 3),
 (106, 5),
 (106, 0),
 (109, 0),
 (110, 0),
 (111, 2),
 (111, 4),
 (111, 3),
 (111, 0),
 (112, 0),
 (113, 0),
 (114, 2),
 (114, 4),
 (114, 3),
 (114, 0),
 (116, 3),
 (116, 0),
 (117, 0),
 (118, 3),
 (118, 0),
 (119, 3),
 (119, 0),
 (120, 2),
 (120, 4),
 (120, 3),
 (120, 5),
 (120, 0),
 (121, 3),
 (122, 2),
 (122, 4),
 (122, 3),
 (122, 0),
 (125, 3),
 (125, 0),
 (126, 3),
 (126, 0),
 (127, 0),
 (128, 0),
 (129, 1),
 (130, 1),
 (131, 3),
 (131, 0),
 (132, 0),
 (134, 0),
 (135, 0),
 (136, 1),
 (137, 2),
 (137, 4),
 (137, 3),
 (137, 0),
 (138, 3),
 (138, 0),
 (139, 3),
 (139, 0),
 (140, 3),
 (143, 3),
 (143, 0),
 (144, 2),
 (144, 4),
 (144, 3),
 (144, 5),
 (144, 0),
 (145, 2),
 (145, 4),
 (145, 3),
 (145, 0),
 (146, 1),
 (149, 0),
 (150, 0),
 (151, 0),
 (152, 2),
 (152, 4),
 (152, 3),
 (152, 5),
 (152, 0),
 (153, 3),
 (155, 1),
 (156, 3),
 (157, 3),
 (158, 3),
 (158, 0),
 (159, 1),
 (160, 0),
 (161, 1),
 (162, 1),
 (165, 2),
 (165, 4),
 (165, 3),
 (165, 5),
 (165, 0),
 (166, 3),
 (166, 0),
 (168, 0),
 (169, 0),
 (170, 1),
 (171, 2),
 (171, 4),
 (171, 3),
 (171, 0),
 (172, 0),
 (173, 1),
 (174, 2),
 (174, 4),
 (174, 3),
 (174, 0),
 (175, 0),
 (177, 0),
 (178, 1),
 (179, 4),
 (179, 0),
 (180, 3),
 (180, 0),
 (182, 0),
 (184, 2),
 (184, 4),
 (184, 3),
 (184, 5),
 (184, 0),
 (185, 2),
 (185, 4),
 (185, 3),
 (185, 0),
 (187, 3),
 (188, 3),
 (189, 2),
 (189, 4),
 (189, 3),
 (189, 0),
 (190, 0),
 (191, 0),
 (192, 4),
 (192, 0),
 (194, 3),
 (194, 0),
 (195, 1),
 (196, 0),
 (197, 0),
 (198, 3),
 (198, 0),
 (199, 0),
 (201, 0),
 (202, 1),
 (203, 2),
 (203, 4),
 (203, 3),
 (203, 0),
 (204, 1),
 (207, 0),
 (209, 3),
 (209, 0),
 (210, 0),
 (211, 0),
 (213, 0),
 (214, 3),
 (214, 0),
 (215, 1),
 (216, 0),
 (217, 1),
 (218, 0),
 (219, 0),
 (220, 3),
 (221, 3),
 (221, 0),
 (222, 2),
 (222, 4),
 (222, 3),
 (222, 0),
 (223, 1),
 (224, 1),
 (225, 2),
 (225, 4),
 (225, 3),
 (225, 5),
 (225, 0),
 (226, 0),
 (227, 0),
 (229, 1),
 (230, 0),
 (231, 1),
 (232, 0),
 (233, 1),
 (234, 3),
 (236, 2),
 (236, 4),
 (236, 3),
 (236, 5),
 (236, 0),
 (239, 1),
 (240, 3),
 (240, 0),
 (241, 2),
 (241, 4),
 (241, 3),
 (241, 5),
 (241, 0),
 (242, 1),
 (243, 1),
 (244, 2),
 (244, 4),
 (244, 3),
 (244, 5),
 (244, 0),
 (245, 1),
 (247, 0),
 (248, 3),
 (249, 0),
 (250, 0),
 (251, 1),
 (252, 0),
 (253, 0),
 (254, 1),
 (256, 0),
 (257, 1),
 (258, 3),
 (259, 1),
 (260, 3),
 (261, 0),
 (262, 3),
 (263, 3),
 (264, 4),
 (264, 0),
 (265, 3),
 (265, 0),
 (266, 3),
 (267, 0),
 (268, 0),
 (269, 1),
 (270, 1),
 (271, 1),
 (273, 1),
 (274, 1),
 (276, 0),
 (278, 1),
 (279, 1),
 (280, 3),
 (281, 1),
 (282, 1),
 (283, 3),
 (283, 0),
 (284, 3),
 (284, 0),
 (285, 0),
 (286, 0),
 (287, 3),
 (288, 0),
 (289, 3),
 (289, 0),
 (290, 1),
 (291, 1),
 (292, 2),
 (292, 4),
 (292, 3),
 (292, 0),
 (293, 3),
 (294, 2),
 (294, 4),
 (294, 3),
 (294, 5),
 (294, 0),
 (295, 0),
 (297, 0),
 (298, 1),
 (300, 2),
 (300, 4),
 (300, 3),
 (300, 5),
 (300, 0),
 (301, 0),
 (302, 2),
 (302, 4),
 (302, 3),
 (302, 0),
 (303, 0),
 (304, 3),
 (304, 0),
 (306, 0),
 (307, 1),
 (308, 0),
 (309, 2),
 (309, 4),
 (309, 3),
 (309, 5),
 (309, 0),
 (310, 2),
 (310, 4),
 (310, 3),
 (310, 5),
 (310, 0),
 (312, 3),
 (314, 2),
 (314, 4),
 (314, 3),
 (314, 0),
 (316, 3),
 (316, 0),
 (317, 1),
 (318, 0),
 (319, 3),
 (319, 0),
 (320, 1),
 (322, 1),
 (323, 3),
 (324, 0),
 (325, 2),
 (325, 4),
 (325, 3),
 (325, 0),
 (326, 0),
 (330, 1),
 (331, 2),
 (331, 4),
 (331, 3),
 (331, 5),
 (331, 0),
 (332, 0),
 (333, 0),
 (335, 1),
 (336, 0),
 (337, 3),
 (337, 0),
 (338, 3),
 (338, 0),
 (339, 0),
 (340, 0),
 (341, 0),
 (342, 0),
 (343, 1),
 (344, 1),
 (345, 1),
 (346, 2),
 (346, 4),
 (346, 3),
 (346, 0),
 (347, 0),
 (348, 3),
 (349, 0),
 (350, 1),
 (351, 1),
 (352, 0),
 (353, 0),
 (354, 1),
 (355, 0),
 (356, 3),
 (356, 0),
 (357, 1),
 (359, 0),
 (360, 3),
 (361, 2),
 (361, 4),
 (361, 3),
 (361, 5),
 (361, 0),
 (362, 3),
 (363, 3),
 (365, 1),
 (366, 0),
 (367, 0),
 (368, 0),
 (369, 1),
 (371, 1),
 (372, 3),
 (372, 0),
 (373, 1),
 (374, 1),
 (376, 0),
 (377, 3),
 (377, 0),
 (378, 0),
 (379, 0),
 (380, 1),
 (381, 0),
 (382, 0),
 (383, 2),
 (383, 4),
 (383, 3),
 (383, 0),
 (384, 2),
 (384, 4),
 (384, 3),
 (384, 0),
 (385, 0),
 (386, 3),
 (386, 0),
 (387, 1),
 (388, 0),
 (389, 0),
 (390, 0),
 (391, 0),
 (392, 0),
 (393, 3),
 (394, 0),
 (395, 3),
 (396, 2),
 (396, 4),
 (396, 3),
 (396, 0),
 (397, 1),
 (398, 3),
 (399, 0),
 (400, 2),
 (400, 4),
 (400, 3),
 (400, 5),
 (400, 0),
 (401, 1),
 (403, 0),
 (405, 2),
 (405, 4),
 (405, 3),
 (405, 0),
 (406, 3),
 (406, 0),
 (407, 1),
 (408, 1),
 (409, 3),
 (409, 0),
 (410, 1),
 (411, 3),
 (411, 0),
 (412, 2),
 (412, 4),
 (412, 3),
 (412, 0),
 (413, 1),
 (414, 1),
 (415, 1),
 (416, 3),
 (417, 0),
 (419, 1),
 (421, 2),
 (421, 4),
 (421, 3),
 (421, 0),
 (422, 0),
 (424, 0),
 (426, 0),
 (427, 0),
 (428, 3),
 (432, 0),
 (433, 2),
 (433, 4),
 (433, 3),
 (433, 5),
 (433, 0),
 (434, 1),
 (435, 0),
 (436, 2),
 (436, 4),
 (436, 3),
 (436, 0),
 (437, 0),
 (438, 1),
 (440, 0),
 (443, 3),
 (443, 0),
 (444, 0),
 (445, 1),
 (446, 1),
 (447, 0),
 (448, 0),
 (449, 1),
 (452, 3),
 (452, 0),
 (454, 2),
 (454, 4),
 (454, 3),
 (454, 5),
 (454, 0),
 (455, 1),
 (456, 2),
 (456, 4),
 (456, 3),
 (456, 5),
 (456, 0),
 (458, 3),
 (459, 0),
 (460, 3),
 (460, 0),
 (461, 1),
 (462, 0),
 (463, 1),
 (464, 0),
 (465, 1),
 (466, 0),
 (467, 3),
 (467, 0),
 (468, 2),
 (468, 4),
 (468, 3),
 (468, 0),
 (469, 3),
 (470, 0),
 (471, 2),
 (471, 4),
 (471, 3),
 (471, 5),
 (471, 0),
 (472, 1),
 (473, 0),
 (474, 3),
 (476, 3),
 (476, 0),
 (478, 3),
 (479, 3),
 (481, 0),
 (482, 1),
 (483, 0),
 (484, 3),
 (484, 0),
 (485, 0),
 (486, 0),
 (487, 1),
 (489, 1),
 (490, 0),
 (492, 0),
 (493, 3),
 (494, 2),
 (494, 4),
 (494, 3),
 (494, 0),
 (495, 1),
 (496, 1),
 (497, 1),
 (498, 3),
 (498, 0),
 (500, 3),
 (501, 3),
 (502, 2),
 (502, 4),
 (502, 3),
 (502, 5),
 (502, 0),
 (503, 1),
 (504, 3),
 (506, 1),
 (507, 1),
 (508, 4),
 (508, 0),
 (509, 1),
 (510, 1),
 (511, 3),
 (513, 0),
 (514, 3),
 (514, 0),
 (515, 2),
 (515, 4),
 (515, 3),
 (515, 0),
 (516, 1),
 (517, 1),
 (518, 0),
 (519, 0),
 (520, 3),
 (520, 0),
 (521, 2),
 (521, 4),
 (521, 3),
 (521, 0),
 (522, 0),
 (523, 0),
 (524, 2),
 (524, 4),
 (524, 3),
 (524, 5),
 (524, 0),
 (525, 2),
 (525, 4),
 (525, 3),
 (525, 0),
 (526, 1),
 (527, 0),
 (528, 0),
 (529, 2),
 (529, 4),
 (529, 3),
 (529, 0),
 (530, 0),
 (531, 1),
 (532, 0),
 (534, 0),
 (535, 3),
 (536, 0),
 (538, 2),
 (538, 4),
 (538, 3),
 (538, 0),
 (539, 2),
 (539, 4),
 (539, 3),
 (539, 0),
 (541, 1),
 (542, 1),
 (543, 1),
 (544, 3),
 (544, 0),
 (545, 3),
 (545, 0),
 (546, 3),
 (546, 0),
 (547, 1),
 (548, 3),
 (549, 0),
 (550, 1),
 (551, 2),
 (551, 4),
 (551, 3),
 (551, 5),
 (551, 0),
 (552, 1),
 (553, 3),
 (553, 0),
 (554, 0),
 (556, 1),
 (558, 0),
 (559, 1),
 (560, 2),
 (560, 4),
 (560, 3),
 (560, 5),
 (560, 0),
 (561, 0),
 (563, 3),
 (563, 0),
 (564, 4),
 (564, 0),
 (565, 0),
 (566, 1),
 (567, 3),
 (568, 0),
 (569, 3),
 (570, 0),
 (571, 0),
 (572, 0),
 (573, 0),
 (574, 0),
 (575, 0),
 (577, 2),
 (577, 4),
 (577, 3),
 (577, 5),
 (577, 0),
 (578, 1),
 (579, 3),
 (580, 3),
 (581, 0),
 (582, 0),
 (583, 0),
 (584, 1),
 (585, 0),
 (586, 0),
 (587, 2),
 (587, 4),
 (587, 3),
 (587, 5),
 (587, 0),
 (588, 0),
 (589, 2),
 (589, 4),
 (589, 3),
 (589, 5),
 (589, 0),
 (590, 0),
 (592, 0),
 (593, 3),
 (594, 1),
 (595, 0),
 (596, 1),
 (597, 3),
 (597, 0),
 (598, 0),
 (599, 1),
 (600, 2),
 (600, 4),
 (600, 3),
 (600, 5),
 (600, 0),
 (602, 4),
 (602, 0),
 (603, 2),
 (603, 4),
 (603, 3),
 (603, 0),
 (604, 1),
 (605, 3),
 (605, 0),
 (606, 0),
 (608, 3),
 (609, 0),
 (611, 2),
 (611, 4),
 (611, 3),
 (611, 0),
 (612, 2),
 (612, 4),
 (612, 3),
 (612, 5),
 (612, 0),
 (613, 1),
 (615, 0),
 (616, 3),
 (616, 0),
 (617, 1),
 (618, 2),
 (618, 4),
 (618, 3),
 (618, 5),
 (618, 0),
 (620, 0),
 (621, 0),
 (622, 0),
 (623, 1),
 (624, 0),
 (625, 1),
 (626, 2),
 (626, 4),
 (626, 3),
 (626, 5),
 (626, 0),
 (628, 1),
 (629, 0),
 (631, 0),
 (632, 1),
 (633, 1),
 (634, 0),
 (635, 0),
 (636, 0),
 (637, 2),
 (637, 4),
 (637, 3),
 (637, 0),
 (638, 3),
 (639, 1),
 (640, 3),
 (640, 0),
 (642, 1),
 (643, 0),
 (644, 0),
 (645, 2),
 (645, 4),
 (645, 3),
 (645, 0),
 (646, 3),
 (646, 0),
 (647, 1),
 (648, 3),
 (648, 0),
 (651, 0),
 (652, 1),
 (653, 0),
 (654, 0),
 (655, 1),
 (656, 1),
 (658, 3),
 (659, 2),
 (659, 4),
 (659, 3),
 (659, 0),
 (661, 1),
 (662, 3),
 (663, 0),
 (664, 3),
 (664, 0),
 (665, 1),
 (666, 2),
 (666, 4),
 (666, 3),
 (666, 5),
 (666, 0),
 (667, 2),
 (667, 4),
 (667, 3),
 (667, 0),
 (668, 2),
 (668, 4),
 (668, 3),
 (668, 0),
 (669, 3),
 (670, 0),
 (671, 0),
 (673, 3),
 (675, 3),
 (675, 0),
 (676, 0),
 (677, 1),
 (678, 3),
 (679, 2),
 (679, 4),
 (679, 3),
 (679, 0),
 (680, 0),
 (681, 3),
 (681, 0),
 (682, 0),
 (684, 0),
 (685, 1),
 (686, 1),
 (687, 3),
 (687, 0),
 (688, 1),
 (689, 1),
 (690, 0),
 (691, 2),
 (691, 4),
 (691, 3),
 (691, 0),
 (692, 0),
 (693, 0),
 (694, 3),
 (694, 0),
 (696, 2),
 (696, 4),
 (696, 3),
 (696, 5),
 (696, 0),
 (697, 3),
 (697, 0),
 (698, 0),
 (699, 0),
 (700, 1),
 (701, 1),
 (704, 1),
 (705, 2),
 (705, 4),
 (705, 3),
 (705, 0),
 (708, 0),
 (709, 1),
 (710, 1),
 (711, 3),
 (711, 0),
 (712, 0),
 (714, 3),
 (715, 1),
 (716, 3),
 (719, 0),
 (720, 2),
 (720, 4),
 (720, 3),
 (720, 5),
 (720, 0),
 (721, 0),
 (722, 3),
 (722, 0),
 (723, 0),
 (724, 2),
 (724, 4),
 (724, 3),
 (724, 5),
 (724, 0),
 (725, 0),
 (726, 1),
 (727, 1),
 (729, 0),
 (730, 2),
 (730, 4),
 (730, 3),
 (730, 5),
 (730, 0),
 ...]

In [ ]:
df_pref_recipe = pd.DataFrame(pref_recipe, columns=["recipe_id", "pref_id"])

In [ ]:
df_pref_recipe

         recipe_id  pref_id
0                0        0
1                1        1
2                4        0
3                5        1
4                6        1
...            ...      ...
1648194    1174476        3
1648195    1174476        0
1648196    1174477        1
1648197    1174478        1
1648198    1174479        0

[1648199 rows x 2 columns]

In [ ]:
upload_table(df_pref_recipe, "pref_recipe")

Connection lost during batch 0-50000, retrying...
Uploaded 100000/1648199 rows
Uploaded 150000/1648199 rows
Uploaded 200000/1648199 rows
Uploaded 250000/1648199 rows
Uploaded 300000/1648199 rows
Uploaded 350000/1648199 rows
Uploaded 400000/1648199 rows
Uploaded 450000/1648199 rows
Uploaded 500000/1648199 rows
Uploaded 550000/1648199 rows
Uploaded 600000/1648199 rows
Uploaded 650000/1648199 rows
Uploaded 700000/1648199 rows
Uploaded 750000/1648199 rows
Uploaded 800000/1648199 rows
Uploaded 850000/1648199 rows
Uploaded 900000/1648199 rows
Uploaded 950000/1648199 rows
Uploaded 1000000/1648199 rows
Uploaded 1050000/1648199 rows
Uploaded 1100000/1648199 rows
Uploaded 1150000/1648199 rows
Uploaded 1200000/1648199 rows
Uploaded 1250000/1648199 rows
Uploaded 1300000/1648199 rows
Uploaded 1350000/1648199 rows
Uploaded 1400000/1648199 rows
Uploaded 1450000/1648199 rows
Uploaded 1500000/1648199 rows
Uploaded 1550000/1648199 rows
Uploaded 1600000/1648199 rows
Uploaded 1650000/1648199 rows
Full recipe dataset uploaded successfully!

### recipe_ingr

In [ ]:
# recipe_id, ingr_id, quantity, unit

In [9]:
df.columns

Index(['ID', 'Name', 'Instructions', 'Ingredients', 'Total Time', 'Calories',
       'Fat', 'Protein', 'Carbohydrate', 'Label', 'Category'],
      dtype='object')

In [10]:
df['Ingredients'][0]

"[{'name': 'vegetable or chicken stock', 'quantity': 4.0, 'unit': 'cups'}, {'name': 'brown lentils', 'quantity': 1.0, 'unit': 'cup'}, {'name': 'french green lentils', 'quantity': 0.5, 'unit': 'cup'}, {'name': 'celery', 'quantity': 2.0, 'unit': 'stalks'}, {'name': 'carrot', 'quantity': 1.0, 'unit': None}, {'name': 'thyme', 'quantity': 1.0, 'unit': 'sprig'}, {'name': 'kosher salt', 'quantity': 1.0, 'unit': 'teaspoon'}, {'name': 'tomato', 'quantity': 1.0, 'unit': None}, {'name': 'fuji apple', 'quantity': 1.0, 'unit': None}, {'name': 'lemon juice', 'quantity': 1.0, 'unit': 'tablespoon'}, {'name': 'extra-virgin olive oil', 'quantity': 2.0, 'unit': 'teaspoons'}, {'name': 'black pepper', 'quantity': None, 'unit': None}, {'name': 'whole-wheat lavash or flour tortillas', 'quantity': 3.0, 'unit': 'sheets'}, {'name': 'turkey breast', 'quantity': 0.75, 'unit': 'pound'}, {'name': 'bibb lettuce', 'quantity': 0.5, 'unit': 'head'}]"

In [11]:
query_ingredient = "SELECT ingr_id, ingr_name FROM ingredient;"
ingredient_df = pd.read_sql(query_ingredient, engine)

In [12]:
ingredient_df

        ingr_id                                          ingr_name
0             1                                  canfruit cocktail
1             2                               red cinnamon candies
2             3                         good quality matcha powder
3             4                             millet or white quinoa
4             5                                 brown sugar-packed
...         ...                                                ...
186896   186897                                  pizza dough yeast
186897   186898                     cauliflower or broccoli floret
186898   186899          vegetable stock or chicken stock or broth
186899   186900                 instant mint-chocolate pudding mix
186900   186901  apricot preserve or raspberry preserve or pres...

[186901 rows x 2 columns]

In [13]:
def normalize_ingredient_name(name):
    return name.strip().replace("'", "''").lower()

In [14]:
ingredient_map = {row["ingr_name"].strip().lower(): row["ingr_id"] for _, row in ingredient_df.iterrows()}

In [15]:
ingredient_map

{'canfruit cocktail': 1,
 'red cinnamon candies': 2,
 'good quality matcha powder': 3,
 'millet or white quinoa': 4,
 'brown sugar-packed': 5,
 'basic halvah': 6,
 'cooked artichoke heart': 7,
 'lemon grated lemon': 8,
 'organic chicken': 9,
 'ylang ylang': 10,
 'white vinegar and water': 11,
 'triple cereal': 12,
 'soy sauce or soy sauce': 13,
 'tangy onion paratha': 14,
 'breadcrumb or panko breadcrumb': 15,
 'flour butter mixed': 16,
 'celery salt or seasoning salt': 17,
 'date bread mix': 18,
 'shake worcestershire sauce': 19,
 'fish or shrimp or clam': 20,
 'indio marionberry vodka': 21,
 "clark''s barbecue sauce": 22,
 'vanilla mousse': 23,
 'ramen or instant noodle or noodle': 24,
 'harvest or sweet onion': 25,
 'strawberry-vin santo sauce': 26,
 'blood orange italian soda': 27,
 'rosenborg beelablu cheese': 28,
 'sunflower seed or kernal': 29,
 'tomato sauce or tomato mushroom sauce': 30,
 'active yeast or bread machine yeast': 31,
 'wormwood bitter': 32,
 'monterey jack cheese': 33,
 'granolla': 34,
 'green seaweed flake': 35,
 'ham or baked ham': 36,
 'italian sausage ravioli': 37,
 'garlic or red pepper butter': 38,
 'baby red-skinned or baby yukon gold potatoe': 39,
 'pitted green or black olive': 40,
 'maraschino cherry or cherry': 41,
 'butter toffee or honey glazed sliced almond': 42,
 'sausga': 43,
 'cherry vanilla soda': 44,
 'lemon syrup': 45,
 'sambal': 46,
 'vegan mozzarella cheese or vegan mozzarella cheese or vegan parmesan cheese': 47,
 'salsa or chili sauce': 48,
 'velveeta or cheese-food': 49,
 'fatty fish-': 50,
 'queso fresco or american cheese': 51,
 'loaf unsliced round bread': 52,
 'extra lg noodle': 53,
 'navan vanilla liqueur': 54,
 'canshormel no-bean chili': 55,
 'constarch': 56,
 'tomato each broccoli or cherry tomato': 57,
 'garlic pepper salt': 58,
 'frankenberry cereal': 59,
 'applewood peppered bacon': 60,
 'canola spray': 61,
 'polvere di cacao': 62,
 'boysenberry tea': 63,
 'bramley applesauce': 64,
 'citrus-cumin vinaigrette': 65,
 'bluefin or yellowfin tuna steak': 66,
 'mixture of red': 67,
 'luxardo maraschino cherry liqueur': 68,
 'chilled shortening': 69,
 'lemon or yuzu pepper paste': 70,
 'mexican ranch or ranch dressing': 71,
 'cream cheese or soft cheese or butter': 72,
 'white raw rice': 73,
 'cherry preserve': 74,
 'fluid tanqueray gin': 75,
 'mango passion fruit yogurt': 76,
 'red pepper oil': 77,
 'tea black currant': 78,
 'mccormick mediterranean spiced salt': 79,
 'beef soup bone': 80,
 'green chile powder': 81,
 'garlic-flavored oil': 82,
 'cocoa powder bitter': 83,
 'salt pepper cone': 84,
 'monte pea and carrot': 85,
 'lemon zest or lemongras': 86,
 'zest strips from limes': 87,
 'tomatoes parsley': 88,
 'natural bacon bit': 89,
 'sweet almond milk': 90,
 'domestic loin lamb chop': 91,
 'cherry kool aid': 92,
 'sambal tomat': 93,
 'corn syrup or dark': 94,
 'japanese soba': 95,
 'vegetable oil or pot': 96,
 'candy-coated chocolate-covered peanut': 97,
 'creole-style mustard': 98,
 'popsicle molds': 99,
 'milk chocolate or chip': 100,
 'xagave or sweetener': 101,
 'port vinaigrette': 102,
 'petite diced or crushed tomatoe': 103,
 'bottlestsingtao beer': 104,
 'yellow eye or navy bean': 105,
 'vanilla turbinado sugar': 106,
 'ice cube, handful': 107,
 'lemoncello': 108,
 '-cheese or cheese': 109,
 'homemade chocolate syrup': 110,
 'chicken bolion cube': 111,
 'water or vegetable liquid': 112,
 'red chili or serrano chili': 113,
 'strawberries or raspberrie or blueberry or blackberry': 114,
 'firm ripe apricots': 115,
 'rice or cider vinegar': 116,
 'ovaltine chocolate malt powder': 117,
 'parsley or beets or salad greens': 118,
 'brut sparkling wine or champagne': 119,
 'citru marinade': 120,
 'chocolate angel delight mix': 121,
 'cajun kielbasa': 122,
 'strawberries by weight sugar': 123,
 'chocolate caramel-covered wafer': 124,
 'seafood halibut or shrimp or lump crabmeat clams or mussels': 125,
 'yabbie meat or crawfish meat': 126,
 'brisket or beef shank': 127,
 'shallot': 128,
 'chili or kidney bean': 129,
 'white -meat chicken quarter or chicken breast': 130,
 'packed boston lettuce leave': 131,
 'chicken half-breast': 132,
 'garlic powder or onion powder': 133,
 'crackling': 134,
 'gm or butter': 135,
 'yeast water or sake': 136,
 'thyme and greek oregano': 137,
 'pineapple or mango juice': 138,
 'newman-o or chocolate sandwich cookie': 139,
 'jalapeno or green chile': 140,
 'gold medal wondra flour': 141,
 'chocolate syrup or caramel sauce': 142,
 'italian lentil or french lentil': 143,
 'chuck steak or topside steak': 144,
 'red-wine vinegar or sherry vinegar': 145,
 'crabcake mix': 146,
 'chili meat': 147,
 'chestnut or pecan halve or cheese': 148,
 'dashe clove': 149,
 'mock mascarpone': 150,
 'banana or peache': 151,
 'cocoanut flavoring': 152,
 'pine kernel pine nut': 153,
 'agar-agar flakes': 154,
 'water, barely cover potatoes': 155,
 'cream cheese or yogurt or cream': 156,
 'plum tomatoe with juice': 157,
 'flavor hummu': 158,
 'red or brown skinned pear': 159,
 'instant regular or oatmeal': 160,
 'pork or bulk sausage': 161,
 'vanilla or almond or rum extract': 162,
 'mozzarella cheese substitute': 163,
 'merlot salt': 164,
 'marashino cherrie': 165,
 'mint juice of lime': 166,
 'honey salt pepper': 167,
 'diet orange jello': 168,
 'seasoning meat': 169,
 'chili garlic lime': 170,
 'dill sauce': 171,
 'honey or tablespoon agave nectar': 172,
 'belgioioso mascarpone cheese': 173,
 'seitan cutlet': 174,
 'lite coconut cream': 175,
 'bottled pimiento-stuffed green olives': 176,
 'eggplant or kabocha eggplant or kabocha squash': 177,
 'soy sauce': 178,
 'nonstick cooking spray or butter or oil': 179,
 'sweet chestnut': 180,
 'gourmet sanding sugar': 181,
 'watermelon jello mix': 182,
 'energy drink or seltzer water': 183,
 'prickly pears': 184,
 "walnut minced confectioner'' sugar": 185,
 'egg and milk': 186,
 'oshibako': 187,
 'mango green': 188,
 'remoulade': 189,
 'tomatillo, husk': 190,
 'bulgarian style whole buttermilk': 191,
 'pastry case': 192,
 'okra cooked with tomatoe': 193,
 'bar heath bar': 194,
 'potato-cut': 195,
 'lamb chop or mutton chop': 196,
 'pepper and additional salt': 197,
 'grnd veal or grnd turkey': 198,
 'beverages, carbonated, ginger ale': 199,
 'nacho chips or frito scoops': 200,
 'handful fresh chive': 201,
 'dried sweetened coconut': 202,
 'veal escallope': 203,
 'berrie fresh seasonal': 204,
 'iceberg lettuce or chop': 205,
 'pecarino cheese': 206,
 'chinese pecan': 207,
 'jello with fruit': 208,
 'oil cook chicken': 209,
 'dark chocolate or baking chocolate': 210,
 'instant cornbread mix': 211,
 "baker''s semi-sweet chocolate or bitter chocolate": 212,
 'angu sirloin': 213,
 'focaccia or english muffin': 214,
 'oil or fry broccoli': 215,
 'spear baby corn': 216,
 'winter mix veggie': 217,
 'pure sesame oil': 218,
 'recipe orange cream frosting': 219,
 'mexican melting cheese': 220,
 'mexican asadero cheese': 221,
 'wheat or multigrain bread': 222,
 'honey bunche oat': 223,
 'chipotle chile-flavored olive oil': 224,
 'cranberry loaf cake': 225,
 'rice vinegar or mirin or white vinegar': 226,
 'homemade or vanilla ice cream': 227,
 'stove top type stuffing': 228,
 'concentrated pineapple juice': 229,
 'sweet relish sweet pickle': 230,
 'collins glass': 231,
 'butter margarine or oil': 232,
 'sunflower or brazil nut oil': 233,
 'spinach and kale mix': 234,
 'sesame oil or oil': 235,
 'head savoy or napa cabbage': 236,
 'apricot glaze or apricot jam': 237,
 'classic coke': 238,
 'egg roll wrapper': 239,
 'pastini': 240,
 'green onion-parmesan popovers': 241,
 'chicken breast or pork': 242,
 'zealand cockle': 243,
 'vine-rippened tomatoe': 244,
 'vanilla-flavored yogurt': 245,
 'duck or goose neck': 246,
 'walnut and cinnamon': 247,
 'knorr bearnaise sauce mix': 248,
 'fry pepper': 249,
 'dill pickle or jalapeno': 250,
 '-cacao bitter chocolate': 251,
 'krusteez buttermilk pancake mix': 252,
 'orange squash or sweet potatoe or pumpkin': 253,
 'seasoning salt or salt and pepper or parsley': 254,
 'gram cracker or cookie': 255,
 'pineapple rings or pineapple': 256,
 'red lentil': 257,
 'parmigiano or romano cheese': 258,
 'meats': 259,
 'ginger sesame dressing': 260,
 'tomato flavored tortilla': 261,
 'mililitre cognac': 262,
 'rondale cheese with pepper or alouette cheese': 263,
 'chicken mold': 264,
 'fork-stirred unbleached all-purpose flour': 265,
 'herbe de provence or thyme': 266,
 'gumbo file powder': 267,
 'chocolate flavor instant': 268,
 'rice or rice noodles and lime': 269,
 'pekin duck breasts': 270,
 'deli style corned beef': 271,
 "libby''s solid pack pumpkin": 272,
 'soft hearty white bread': 273,
 'veal rib chop or loin chop': 274,
 'onion or garlic powder': 275,
 'chli powder': 276,
 'good bourbon': 277,
 'garlic oil or shallot oil': 278,
 'pb': 971,
 'marsala or red wine': 279,
 'chive or kucai': 280,
 'blackberry jam or syrup': 281,
 'lite luncheon meat': 282,
 'motzerella finely shredded cheese': 283,
 'english muffin raisin': 284,
 'mustard oil or olive oil': 285,
 'blood orange peel': 286,
 'crostini toast': 287,
 'horseradish cheddar cheese': 288,
 'cabana': 289,
 'nam plah': 290,
 'oscar mayer regular meat': 291,
 'cilantro or herb': 292,
 'mixed berries and fruit': 293,
 'speck ham': 294,
 'oat flake': 295,
 'lemon verbena or mint leaf': 296,
 'bakery-style sandwich bun butter': 297,
 'nut or raisin or fruit or coconut or candy': 298,
 'pineapple chunk with juice': 299,
 'blue gingerroot': 300,
 'maple flavor': 301,
 'herb tomato sauce': 302,
 'yellow potatoes': 303,
 'golf ball-size ginger': 304,
 'packagegaspar linguica sausage': 305,
 'blue cheese minced parsley': 306,
 'xylitol or sugar': 307,
 'dolce flour': 308,
 'chili powder dark': 309,
 'peanut oil or nut oil': 310,
 'cocktail sauce with horseradish': 311,
 'carrot, cucumber or celery': 312,
 'radiatore or rotini pasta': 313,
 'citru tequila': 314,
 'oregano season': 315,
 'rolling pin': 316,
 'vanilla extract or mint extract': 317,
 'fresno chile or red jalapeno chile': 318,
 'fava leave': 319,
 'chocolate candy or chocolate-covered peanut or chocolate-covered almond or crispy chocolate decorative candie': 320,
 'earthy red wine': 321,
 'kiwi fruit': 322,
 'cognac or rum or brandy': 323,
 'berber': 324,
 'orange or tangerine or satsuma orange': 325,
 'vegan or corn oil': 326,
 'italian eggplants': 327,
 'rabbit loin': 328,
 'salad cucumber': 329,
 'celery raw beetroot green': 330,
 'white flour or oatmeal or cornmeal': 331,
 'santa maria tri-tip seasoning': 332,
 'oscar mayer pepperoni': 333,
 'avocado, horseradish spread': 334,
 'honey jack daniel': 335,
 'echinacea extract': 336,
 'chicken fajita strip': 337,
 'laughing cow swis cheese': 338,
 'recipe biscuit dough': 339,
 'mix herbs': 340,
 'strawberry-flavoured cream cheese': 341,
 'chocate chunk': 342,
 'half or fish black rockfish': 343,
 'cream vanilla frosting': 344,
 'chinese or shirataki noodle': 345,
 'jack flakey biscuit': 346,
 'dry-cure bacon': 347,
 'egg icing': 348,
 'worch sauce': 349,
 'milk canned lowfat milk': 350,
 'butter flavored cracker': 351,
 'recipe brioche dough': 352,
 'red cinnamon candies or gumdrop': 353,
 'whey': 354,
 'white port or white wine': 355,
 'falernum syrup': 356,
 'rice or bulgur or wheat berrie or barley': 357,
 'pomegranate molasse or grenadine': 358,
 'fish fillet such flounder or orange roughy': 359,
 'kinako and sugar or kuromitsu and kinako': 360,
 'celery stalk celery stem': 361,
 'mediumripe banana': 362,
 'cornbread stuffing mix or seasoned stuffing mix': 363,
 'guava paste or jam': 364,
 'soy hot dog': 365,
 'hickory flavoring': 366,
 'currant or red currant jelly': 367,
 'ham and pork tortellini': 368,
 'milk or water or orange juice': 369,
 'local apple': 370,
 'jarsproces cheese sauce': 371,
 'jalapena pepper': 372,
 'whip or reddi-wip topping': 373,
 'turkey lunch meat': 374,
 'drizzle soy sauce': 375,
 'chickpea or garbanzo': 376,
 'springform pan or rolling pin or mixing or roasting pan': 377,
 'flour or wheat bran or cornmeal': 378,
 'sweet bread roll': 379,
 'meat or shellfish sausage, pork': 380,
 'splenda or sugar free sweetener': 381,
 'avocado or olive oil': 382,
 'green papayapeeled': 383,
 'vegemite salt pepper': 384,
 'garlic bulb': 385,
 'cocoa nib or bitter chocolate chip': 386,
 'canola oil or extra-light vegetable oil spread': 387,
 'vegetarian ham': 388,
 'mint leaves or orange zest': 389,
 'honey dijonnaise mustard': 390,
 'jigger gin': 391,
 'wheat roll': 392,
 'amaretto liqueur or malvasia or sweet dessert wine': 393,
 "lawry''s seasoing": 394,
 'english puddings': 395,
 'white fat': 396,
 'savory herb': 397,
 'spinach or whole-wheat tortilla': 398,
 'cocktail smokie': 399,
 'swanson thai ginger stock': 400,
 'cast-iron skillet pastry': 401,
 'nut or base filling': 402,
 'chicken brest': 403,
 'sweet bell pepper or celery': 404,
 'flax seed or sesame seed': 405,
 'italian chopped tomatoe': 406,
 'gm lavang': 407,
 'chocolate-hazelnut spread': 408,
 'micro shiso': 409,
 'apricot all-fruit jam': 410,
 'serrano pepper or salt': 411,
 'crisp harvest apple': 412,
 'vegetable broth or parve chicken broth or chicken stock': 413,
 'sereh pwdr': 414,
 'broiler red potatoe': 415,
 'skinner medium shell': 416,
 'pouche corn bread mix': 417,
 'crispy pork lard': 418,
 'enoki mushroom': 419,
 'chunk chocolate': 420,
 'butterscotch instant mousse': 421,
 'broccoli or spinach or zucchini': 422,
 'yellow zucchini or yellow squash': 423,
 'amish noodle': 424,
 'artisan, sourdough or french bread': 425,
 'whip topping or creme whipped': 426,
 "sweet''n low or sugar": 427,
 'karo lite syrup': 428,
 'groumet garlic basil seasoning': 429,
 'beef and italian sausage': 430,
 'sardine skinles': 431,
 'beef brisket or belly': 432,
 'peanut or cashew butter': 433,
 'banana lily flower': 434,
 'pistachio halvah or halvah': 435,
 'heavy cream or eggnog': 436,
 'canflakey refrigerated buttermilk biscuit': 437,
 'cedar shake': 438,
 'chihuahua cheese or monterey jack cheese': 439,
 'tomatoes, pulp': 440,
 'chili warm bean': 441,
 'ramen salad': 442,
 'instant chicken bouillon granule or vegetable stock powder': 443,
 'patty shell': 444,
 'flax egg or egg white': 445,
 'peperoncino picante sauce': 446,
 'wild blend rice': 447,
 'lea perrin sauce': 448,
 'cooking yogurt or yogurt': 449,
 'red burgundy wine or red': 450,
 'scallions or cream': 451,
 'sambhaar': 452,
 'heirloom geese': 453,
 'twinkie are imitation twinkie': 454,
 'tabasco sauce or chili ketchup': 455,
 'loaf muffaletta bread': 456,
 'tagliatelle or fettuccine': 457,
 'couscou or white rice': 458,
 'snow pea or chinese pea pod': 459,
 'flax powder': 460,
 'grnd annatto seed': 461,
 'rosemary leaves or dried': 462,
 'parsley leave stem': 463,
 'dark brown mustard': 464,
 'vanilla extract or brandy': 465,
 'stale or bread': 466,
 'orange oil or zest': 467,
 'wheat cereal biscuit': 468,
 'blue cheese or beenleigh': 469,
 'katakuriko or cornstarch': 470,
 'onion and pepper': 471,
 'extra virgn olive oil': 472,
 'chocolate square': 473,
 'cape gooseberry jam or bitter orange marmalade': 474,
 'handf juniper berrie': 475,
 'wok oil or vegetable oil': 476,
 'flour blended with water': 477,
 'bright red paprika': 478,
 'yellow tubed icing': 479,
 'eggs large eggs': 480,
 'morton season': 481,
 'green or gold zucchini': 482,
 'israeli couscous or acini di pepe': 483,
 'chinese wombok cabbage or savoy cabbage': 484,
 'red or green cherrie': 485,
 'coconut flour or wheat pastry flour': 486,
 'chicken or beef bouillon': 487,
 'kudzu leaves': 488,
 'mc cormick wortshire seasoning': 489,
 'extra breadcrumbs': 490,
 'cayenne based hot sauce': 491,
 'arugula or rocket': 492,
 'parmesan cheese or cheese rind': 493,
 'chicken spice': 494,
 'round red potatoe': 495,
 'grnd veal or beef and pork': 496,
 'peach-mango salsa': 497,
 'butter lemon curd': 498,
 'sweet eating apple': 499,
 'yellow wheat noodle': 500,
 'cayenne pepper seasoning': 501,
 'meat juices from beef or taste': 502,
 'coriander spice': 503,
 'mexican queso fresco or feta or salted farmer cheese': 504,
 'joy dishwashing soap or liquid dishwashing soap': 505,
 'instant pudding powder': 506,
 'zucchini or potato': 507,
 'crinkle-cut french frie': 508,
 'pork scrap': 509,
 'mint green tea': 510,
 'egg substitute or egg and egg white': 511,
 'fishsauce or soy sauce': 512,
 'tomotoe': 513,
 'grey sole fillet': 514,
 'cake mix spice': 515,
 'mangetout': 516,
 'corn starch paste': 517,
 'boxlong macaroni': 518,
 'white whole wheat or all-purpose flour': 519,
 'clorox ii powdered bleach': 520,
 'arrowroot or vanilla cookie': 521,
 "m m''s or chocolate chip": 522,
 'packagefordhook frozen lima bean': 523,
 'yogurt-avocado dressing': 524,
 'mustard salt and pepper': 525,
 'rice uncooked rice': 526,
 'spice island grinder garlic': 527,
 'nuts or peanuts': 528,
 'goya cubito': 529,
 'fresh okra, cut crosswise into pieces or okra': 530,
 'milk chocolate melts': 531,
 'cilantro lime rice': 532,
 'taste cream': 533,
 'dozen periwinkle': 534,
 'white sugar substitute': 535,
 'drumsticks': 536,
 'pecans, shredded coconut': 537,
 'tabasco honey': 538,
 'water apple tarte tatin': 539,
 'toblerone milk chocolate or toblerone dark chocolate': 540,
 'brummel brown light butter': 541,
 'hershey mini bar': 542,
 'chili mayonaisse or mayonaisse flavored with mustard or horseradish': 543,
 'nougatine or caramel-based candy': 544,
 'curry or coriander powder': 545,
 'organic alfalfa seed': 546,
 'extra-lean beef': 547,
 'terry chocolate orange': 548,
 'sauce of choice, celery or carrot': 549,
 'vegan margarine or butter': 550,
 'soy or teriyaki sauce': 551,
 'sauce or harissa': 552,
 'recipe mashed potatoe': 553,
 'pomona universal pectin': 554,
 'bar ghirardelli bitter chocolate': 555,
 'peacheshalved': 556,
 'budweiser': 557,
 'sriracha or pepper sauce': 558,
 'fingerling potatoe or potatoe': 559,
 'fee brothers peach bitters or bitters': 560,
 "barb''s special sweet bread": 561,
 'piglet': 562,
 'sara lee croissant': 563,
 'pineapple grapefruit juice': 564,
 'noodle shell': 565,
 'lettuce, onion': 566,
 'artichoke halve or quarter': 567,
 'cast-iron skillet or nonstick skillet': 568,
 'bone -in country ham': 569,
 'lata de calabaza': 570,
 'karashi mustard': 571,
 'sm raisin': 572,
 'melted butter or butter-flavored cooking spray': 573,
 'herb dip': 574,
 'fish or clam broth': 575,
 'fiesta taco dinner bake': 576,
 'canchili ready tomatoe': 577,
 'vinegar white wine': 578,
 'cube consomme': 579,
 'truffle oil or extra-virgin olive oil': 580,
 'stevia extract or sugar': 581,
 'saute expres': 582,
 'thyme or sage sprig': 583,
 'carrot, and cucumber': 584,
 'squash ravioli': 585,
 'baby carrot or baby beet': 586,
 'red or rice wine vinegar': 587,
 'chinese pa pod': 588,
 'tarragon or sage': 589,
 'squeeze parkay margarine': 590,
 'yogurt or mayonaisse': 591,
 'tomatoe water': 592,
 'gummy frog': 593,
 "egg muller''s": 594,
 'yellow gumdrop fruit': 595,
 'coffee, mug': 596,
 'skinles turkey meat': 597,
 'peach puree': 598,
 'solid packed pumpkin puree': 599,
 'juice grated from coconut': 600,
 'corn cob': 601,
 'cornstarch or cleargel': 602,
 'christian brother brandy': 603,
 'authentic cuban rolls': 604,
 'peache or apricot': 605,
 'muscatel': 606,
 'yellow neck squash or zucchini': 607,
 "goat''s cheese garrotxa": 608,
 'fluid anisette': 609,
 'grace pumpkin noodle soup': 610,
 'juice extractor': 611,
 'brown sugar or splenda mix sugar substitute': 612,
 'pointy stick': 613,
 'lemon pepper, salt or herbs': 614,
 'spinach leave or kale': 615,
 'crusty dinner roll': 616,
 'arbol chile powder or cayenne pepper': 617,
 'cucumber, spears celery': 618,
 'ritz cracker rolled': 619,
 'lavender sugar with vanilla': 620,
 'wreckfish or snapper fillets': 621,
 'organic sour cream or mozzarella cheese or feta cheese': 622,
 'chicken or turkey or pork': 623,
 'pancake powdered mix': 624,
 'pan': 625,
 'premade oreo pie crust': 626,
 'diced cooked chicken': 627,

In [16]:
def generate_ingr_recipe(df):
    #print(label_map)
    recipe_ingr_data = []
    # Iterate through each recipe
    for _, row in df.iterrows():
        recipe_id = row["ID"]
        ingredients = row["Ingredients"]
        
        if pd.isna(ingredients):  # Handle missing labels
            continue

        ingredients_list = ast.literal_eval(ingredients)  # Convert string to list

        for item in ingredients_list:
            ingredient_name = normalize_ingredient_name(item["name"])
            quantity = item.get("quantity", None)  # Get quantity, default to None
            unit = item.get("unit", None)  # Get unit, default to None

            # 🔹 Find ingr_id from the real database mapping
            ingr_id = ingredient_map.get(ingredient_name)

            if ingr_id:
                recipe_ingr_data.append((recipe_id, ingr_id, quantity, unit))
            else:
                print(f"⚠️ Warning: Ingredient '{ingredient_name}' still not found!")

    return recipe_ingr_data

In [17]:
missing_ingredients = set()
for ingredients in df["Ingredients"].dropna():
    ingredients_list = ast.literal_eval(ingredients)  # Convert string to list

    for item in ingredients_list:
        ingredient_name = normalize_ingredient_name(item["name"])

        if ingredient_name not in ingredient_map:
            missing_ingredients.add(ingredient_name)

# 🔹 Print missing ingredients
print("⚠️ Missing ingredients:", missing_ingredients)

⚠️ Missing ingredients: set()

In [18]:
len(missing_ingredients)
# 3694

0

In [19]:
recipe_ingr_data = generate_ingr_recipe(df)

In [20]:
df_recipe_ingr = pd.DataFrame(recipe_ingr_data, columns=["recipe_id", "ingr_id", "quantity", "unit"])

In [21]:
df_recipe_ingr

         recipe_id  ingr_id quantity      unit
0                0    90699      4.0      cups
1                0   155455      1.0       cup
2                0   108948      0.5       cup
3                0   113066      2.0    stalks
4                0    18365      1.0      None
...            ...      ...      ...       ...
9446508    1174479   170574       34  teaspoon
9446509    1174479    11856       44  teaspoon
9446510    1174479   109775       34      None
9446511    1174479   126876       49      None
9446512    1174479   108892       34      cups

[9446513 rows x 4 columns]

In [22]:
"""
Fatal error uploading data: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "recipe_ingr_pkey"
DETAIL:  Key (recipe_id, ingr_id)=(1, 65614) already exists."""

print(df_recipe_ingr[(df_recipe_ingr["recipe_id"] == 1) & (df_recipe_ingr["ingr_id"] == 65614)])

    recipe_id  ingr_id quantity  unit
18          1    65614      3.0  None
34          1    65614     None  None

In [23]:
df_recipe_ingr = df_recipe_ingr.drop_duplicates(subset=["recipe_id", "ingr_id"], keep="first")

In [24]:
df_recipe_ingr

         recipe_id  ingr_id quantity      unit
0                0    90699      4.0      cups
1                0   155455      1.0       cup
2                0   108948      0.5       cup
3                0   113066      2.0    stalks
4                0    18365      1.0      None
...            ...      ...      ...       ...
9446508    1174479   170574       34  teaspoon
9446509    1174479    11856       44  teaspoon
9446510    1174479   109775       34      None
9446511    1174479   126876       49      None
9446512    1174479   108892       34      cups

[9121530 rows x 4 columns]

In [ ]:
import re

def clean_quantity(value):
    """
    Converts quantity values to valid float numbers.
    - Handles ranges like '10-15' → converts to 10.0 (lower bound).
    - Handles fractions like '1/2' → converts to 0.5.
    - Returns None if conversion is not possible.
    """
    if pd.isna(value) or value is None:
        return None  # Keep null values
    
    value = str(value).strip()  # Ensure it's a string
    
    # Handle ranges like "10-15" → take the first number
    if "-" in value:
        value = value.split("-")[0]

    # Convert fractions like "1/2" to float
    if "/" in value:
        try:
            return float(value.split("/")[0]) / float(value.split("/")[1])
        except:
            return None  # If conversion fails, return None
    
    # Convert normal numbers
    try:
        return float(value)
    except ValueError:
        return None  # If not a valid number, return None

# 🔹 Apply the cleaning function to `quantity` column
df_recipe_ingr["quantity"] = df_recipe_ingr["quantity"].apply(clean_quantity)

# 🔹 Print invalid quantities to debug
invalid_quantities = df_recipe_ingr[df_recipe_ingr["quantity"].isna()]
print("⚠️ Invalid Quantities:", invalid_quantities)

In [26]:
upload_table(df_recipe_ingr, "recipe_ingr")

Uploaded 50000/9121530 rows
Uploaded 100000/9121530 rows
Uploaded 150000/9121530 rows
Uploaded 200000/9121530 rows
Uploaded 250000/9121530 rows
Uploaded 300000/9121530 rows
Uploaded 350000/9121530 rows
Uploaded 400000/9121530 rows
Uploaded 450000/9121530 rows
Uploaded 500000/9121530 rows
Uploaded 550000/9121530 rows
Uploaded 600000/9121530 rows
Uploaded 650000/9121530 rows
Uploaded 700000/9121530 rows
Uploaded 750000/9121530 rows
Uploaded 800000/9121530 rows
Uploaded 850000/9121530 rows
Uploaded 900000/9121530 rows
Uploaded 950000/9121530 rows
Uploaded 1000000/9121530 rows
Uploaded 1050000/9121530 rows
Uploaded 1100000/9121530 rows
Uploaded 1150000/9121530 rows
Uploaded 1200000/9121530 rows
Uploaded 1250000/9121530 rows
Uploaded 1300000/9121530 rows
Uploaded 1350000/9121530 rows
Uploaded 1400000/9121530 rows
Uploaded 1450000/9121530 rows
Uploaded 1500000/9121530 rows
Uploaded 1550000/9121530 rows
Uploaded 1600000/9121530 rows
Uploaded 1650000/9121530 rows
Uploaded 1700000/9121530 rows
Uploaded 1750000/9121530 rows
Uploaded 1800000/9121530 rows
Uploaded 1850000/9121530 rows
Uploaded 1900000/9121530 rows
Uploaded 1950000/9121530 rows
Uploaded 2000000/9121530 rows
Uploaded 2050000/9121530 rows
Uploaded 2100000/9121530 rows
Uploaded 2150000/9121530 rows
Uploaded 2200000/9121530 rows
Uploaded 2250000/9121530 rows
Uploaded 2300000/9121530 rows
Uploaded 2350000/9121530 rows
Uploaded 2400000/9121530 rows
Uploaded 2450000/9121530 rows
Uploaded 2500000/9121530 rows
Uploaded 2550000/9121530 rows
Uploaded 2600000/9121530 rows
Uploaded 2650000/9121530 rows
Uploaded 2700000/9121530 rows
Uploaded 2750000/9121530 rows
Uploaded 2800000/9121530 rows
Uploaded 2850000/9121530 rows
Uploaded 2900000/9121530 rows
Uploaded 2950000/9121530 rows
Uploaded 3000000/9121530 rows
Uploaded 3050000/9121530 rows
Uploaded 3100000/9121530 rows
Uploaded 3150000/9121530 rows
Uploaded 3200000/9121530 rows
Uploaded 3250000/9121530 rows
Uploaded 3300000/9121530 rows
Uploaded 3350000/9121530 rows
Uploaded 3400000/9121530 rows
Uploaded 3450000/9121530 rows
Uploaded 3500000/9121530 rows
Uploaded 3550000/9121530 rows
Uploaded 3600000/9121530 rows
Uploaded 3650000/9121530 rows
Uploaded 3700000/9121530 rows
Uploaded 3750000/9121530 rows
Uploaded 3800000/9121530 rows
Uploaded 3850000/9121530 rows
Uploaded 3900000/9121530 rows
Uploaded 3950000/9121530 rows
Uploaded 4000000/9121530 rows
Uploaded 4050000/9121530 rows
Uploaded 4100000/9121530 rows
Uploaded 4150000/9121530 rows
Uploaded 4200000/9121530 rows
Uploaded 4250000/9121530 rows
Uploaded 4300000/9121530 rows
Uploaded 4350000/9121530 rows
Uploaded 4400000/9121530 rows
Uploaded 4450000/9121530 rows
Uploaded 4500000/9121530 rows
Uploaded 4550000/9121530 rows
Uploaded 4600000/9121530 rows
Uploaded 4650000/9121530 rows
Uploaded 4700000/9121530 rows
Uploaded 4750000/9121530 rows
Uploaded 4800000/9121530 rows
Uploaded 4850000/9121530 rows
Uploaded 4900000/9121530 rows
Uploaded 4950000/9121530 rows
Uploaded 5000000/9121530 rows
Uploaded 5050000/9121530 rows
Uploaded 5100000/9121530 rows
Uploaded 5150000/9121530 rows
Uploaded 5200000/9121530 rows
Uploaded 5250000/9121530 rows
Uploaded 5300000/9121530 rows
Uploaded 5350000/9121530 rows
Uploaded 5400000/9121530 rows
Uploaded 5450000/9121530 rows
Uploaded 5500000/9121530 rows
Uploaded 5550000/9121530 rows
Uploaded 5600000/9121530 rows
Uploaded 5650000/9121530 rows
Uploaded 5700000/9121530 rows
Uploaded 5750000/9121530 rows
Uploaded 5800000/9121530 rows
Uploaded 5850000/9121530 rows
Uploaded 5900000/9121530 rows
Uploaded 5950000/9121530 rows
Uploaded 6000000/9121530 rows
Uploaded 6050000/9121530 rows
Uploaded 6100000/9121530 rows
Uploaded 6150000/9121530 rows
Uploaded 6200000/9121530 rows
Uploaded 6250000/9121530 rows
Uploaded 6300000/9121530 rows
Uploaded 6350000/9121530 rows
Uploaded 6400000/9121530 rows
Uploaded 6450000/9121530 rows
Fatal error uploading data: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type double precision: "10-15"
LINE 1: ...820849, 10341, 13.0, 'teaspoon'), (820850, 44529, '10-15', '...
                                                             ^

[SQL: INSERT INTO recipe_ingr (recipe_id, ingr_id, quantity, unit) VALUES (%(recipe_id__0)s, %(ingr_id__0)s, %(quantity__0)s, %(unit__0)s), (%(recipe_id__1)s, %(ingr_id__1)s, %(quantity__1)s, %(unit__1)s), (%(recipe_id__2)s, %(ingr_id__2)s, %(quantity__2)s ... 73276 characters truncated ... ity__998)s, %(unit__998)s), (%(recipe_id__999)s, %(ingr_id__999)s, %(quantity__999)s, %(unit__999)s)]
[parameters: {'unit__0': 'tablespoon', 'ingr_id__0': 56267, 'recipe_id__0': 820847, 'quantity__0': 1.0, 'unit__1': 'tablespoon', 'ingr_id__1': 76266, 'recipe_id__1': 820847, 'quantity__1': 1.0, 'unit__2': 'piece', 'ingr_id__2': 90451, 'recipe_id__2': 820847, 'quantity__2': 1.0, 'unit__3': 'ml', 'ingr_id__3': 80884, 'recipe_id__3': 820847, 'quantity__3': 30.0, 'unit__4': 'ml', 'ingr_id__4': 106545, 'recipe_id__4': 820847, 'quantity__4': 30.0, 'unit__5': 'pinch', 'ingr_id__5': 91326, 'recipe_id__5': 820847, 'quantity__5': 1.0, 'unit__6': 'piece', 'ingr_id__6': 180207, 'recipe_id__6': 820848, 'quantity__6': 1.0, 'unit__7': 'piece', 'ingr_id__7': 167434, 'recipe_id__7': 820848, 'quantity__7': 1.0, 'unit__8': 'cup', 'ingr_id__8': 175698, 'recipe_id__8': 820848, 'quantity__8': 13.0, 'unit__9': 'piece', 'ingr_id__9': 135821, 'recipe_id__9': 820848, 'quantity__9': 1.0, 'unit__10': 'teaspoon', 'ingr_id__10': 91326, 'recipe_id__10': 820848, 'quantity__10': 0.25, 'unit__11': 'cup', 'ingr_id__11': 93997, 'recipe_id__11': 820848, 'quantity__11': 1.0, 'unit__12': 'cup', 'ingr_id__12': 81187 ... 3900 parameters truncated ... 'recipe_id__987': 820952, 'quantity__987': '1', 'unit__988': 'teaspoon', 'ingr_id__988': 59470, 'recipe_id__988': 820952, 'quantity__988': '1', 'unit__989': 'water glass', 'ingr_id__989': 106545, 'recipe_id__989': 820952, 'quantity__989': '1', 'unit__990': 'piece', 'ingr_id__990': 91139, 'recipe_id__990': 820953, 'quantity__990': '1', 'unit__991': 'external', 'ingr_id__991': 173720, 'recipe_id__991': 820953, 'quantity__991': '5', 'unit__992': 'tablespoon', 'ingr_id__992': 125319, 'recipe_id__992': 820953, 'quantity__992': '4', 'unit__993': 'teaspoon', 'ingr_id__993': 98436, 'recipe_id__993': 820953, 'quantity__993': '1', 'unit__994': 'teaspoon', 'ingr_id__994': 105410, 'recipe_id__994': 820953, 'quantity__994': '1', 'unit__995': 'teaspoon', 'ingr_id__995': 93760, 'recipe_id__995': 820953, 'quantity__995': '1', 'unit__996': 'teaspoon', 'ingr_id__996': 91326, 'recipe_id__996': 820953, 'quantity__996': '0.5', 'unit__997': 'tablespoon', 'ingr_id__997': 4943, 'recipe_id__997': 820953, 'quantity__997': '2', 'unit__998': 'tablespoon', 'ingr_id__998': 132500, 'recipe_id__998': 820953, 'quantity__998': '1', 'unit__999': 'teaspoon', 'ingr_id__999': 10435, 'recipe_id__999': 820953, 'quantity__999': '1'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)

In [27]:
from sqlalchemy.exc import OperationalError, IntegrityError

def upload_table_skip_rows(df_to_upload, table, start_row=0, chunk_size=50000):
    """
    Uploads data in chunks, resuming from a specific row (start_row).
    - Skips syntax errors & continues to the next batch.
    - Automatically resumes from where it left off.
    """
    try:
        for i in range(start_row, len(df_to_upload), chunk_size):
            try:
                with engine.begin() as connection:
                    df_to_upload.iloc[i:i+chunk_size].to_sql(
                        table, connection, if_exists="append", index=False, method="multi"
                    )
                    print(f"✅ Uploaded {i+chunk_size}/{len(df_to_upload)} rows")

            except OperationalError as e:
                print(f"⚠️ Connection lost at batch {i}-{i+chunk_size}, retrying...")
                continue  # Retry next batch

            except IntegrityError as e:
                print(f"⚠️ Skipping batch {i}-{i+chunk_size} due to IntegrityError: {e}")
                continue  # Skip problematic batch

        print("🚀 Full dataset uploaded successfully!")

    except Exception as e:
        print("❌ Fatal error uploading data:", e)

In [28]:
# 🔹 Resume from row 6450000
upload_table_skip_rows(df_recipe_ingr, "recipe_ingr", start_row=6450000)

⚠️ Connection lost at batch 6450000-6500000, retrying...
✅ Uploaded 6550000/9121530 rows
✅ Uploaded 6600000/9121530 rows
✅ Uploaded 6650000/9121530 rows
✅ Uploaded 6700000/9121530 rows
✅ Uploaded 6750000/9121530 rows
✅ Uploaded 6800000/9121530 rows
✅ Uploaded 6850000/9121530 rows
✅ Uploaded 6900000/9121530 rows
✅ Uploaded 6950000/9121530 rows
✅ Uploaded 7000000/9121530 rows
✅ Uploaded 7050000/9121530 rows
✅ Uploaded 7100000/9121530 rows
✅ Uploaded 7150000/9121530 rows
✅ Uploaded 7200000/9121530 rows
✅ Uploaded 7250000/9121530 rows
✅ Uploaded 7300000/9121530 rows
✅ Uploaded 7350000/9121530 rows
✅ Uploaded 7400000/9121530 rows
✅ Uploaded 7450000/9121530 rows
✅ Uploaded 7500000/9121530 rows
✅ Uploaded 7550000/9121530 rows
✅ Uploaded 7600000/9121530 rows
✅ Uploaded 7650000/9121530 rows
✅ Uploaded 7700000/9121530 rows
✅ Uploaded 7750000/9121530 rows
✅ Uploaded 7800000/9121530 rows
✅ Uploaded 7850000/9121530 rows
✅ Uploaded 7900000/9121530 rows
✅ Uploaded 7950000/9121530 rows
✅ Uploaded 8000000/9121530 rows
✅ Uploaded 8050000/9121530 rows
✅ Uploaded 8100000/9121530 rows
✅ Uploaded 8150000/9121530 rows
✅ Uploaded 8200000/9121530 rows
✅ Uploaded 8250000/9121530 rows
✅ Uploaded 8300000/9121530 rows
✅ Uploaded 8350000/9121530 rows
✅ Uploaded 8400000/9121530 rows
✅ Uploaded 8450000/9121530 rows
✅ Uploaded 8500000/9121530 rows
✅ Uploaded 8550000/9121530 rows
✅ Uploaded 8600000/9121530 rows
✅ Uploaded 8650000/9121530 rows
✅ Uploaded 8700000/9121530 rows
✅ Uploaded 8750000/9121530 rows
✅ Uploaded 8800000/9121530 rows
✅ Uploaded 8850000/9121530 rows
✅ Uploaded 8900000/9121530 rows
✅ Uploaded 8950000/9121530 rows
✅ Uploaded 9000000/9121530 rows
✅ Uploaded 9050000/9121530 rows
✅ Uploaded 9100000/9121530 rows
✅ Uploaded 9150000/9121530 rows
🚀 Full dataset uploaded successfully!