In [2]:
import pandas as pd
import glob

In [3]:
asd_df = pd.read_parquet('Recipe1M/final_recipes_data.parquet', engine='pyarrow')

In [4]:
asd_df

,Name,Instructions,total_time,calories,protein,fat,sugar,ingredients,desc
0,Yogurt Parfaits,[Layer all ingredients in a serving dish.],NaN,332.06,28.30,8.76,20.82,"[{'name': 'yogurt, greek, plain, nonfat', 'qua...",
1,"Salt Free, Low Cholesterol Sugar Cookies Recipe","[Cream sugar and butter together till smooth.,...",NaN,3567.77,57.02,175.08,106.92,"[{'name': 'sugars, granulated', 'quantity': 0....",
2,Honey Sriracha Chicken Wings,"[Preheat oven to 400 degrees F., In a large bo...",50.0,3286.10,242.97,225.81,48.16,"[{'name': 'chicken, broilers or fryers, wing, ...",
3,Shrimp and Caper Salad,"[In a large bowl, toss the shrimp, green onion...",60.0,3066.25,188.09,251.61,4.95,"[{'name': 'crustaceans, shrimp, raw (not previ...",
4,Natural Peanut Butter Chocolate Bon Bons,[Measure out the cocoa powder into a mixing bo...,120.0,16252.00,271.44,272.88,3385.56,"[{'name': 'cocoa, dry powder, unsweetened', 'q...",
...,...,...,...,...,...,...,...,...,...
51230,Granola Supreme,"[Preheat oven to 250 deg., Grease 2 cookie she...",15.0,118766.06,301.60,6700.97,14037.07,"[{'name': 'oats', 'quantity': 6.0, 'unit': 'cu...",
51231,Almond Bark Candy,"[Melt chocolate until smooth., Add raisins and...",NaN,17910.27,443.05,988.45,316.54,"[{'name': 'spartan, real semi-sweet chocolate ...",
51232,Chocolate Crumble,"[Heat the oven to 375F or 350F on convection.,...",20.0,1405.58,16.08,79.73,88.81,"[{'name': 'butter, without salt', 'quantity': ...",
51233,Cran-Apple White Chocolate Popcorn,[Melt chocolate in large bowl set over pot of ...,NaN,14789.21,47.81,139.83,3151.56,"[{'name': 'spartan, real semi-sweet chocolate ...",
51234,Extremely Easy and Quick - Namul Daikon Salad,[Julienne the daikon and squeeze out the exces...,NaN,199.23,3.25,18.23,2.92,"[{'name': 'radishes, raw', 'quantity': 150.0, ...",

In [5]:
"""df_sorted = asd_df.sort_values(by='Name')"""

"df_sorted = asd_df.sort_values(by='Name')"

### Read Parquet File

In [6]:
# Use glob to match all parquet files
files = glob.glob('Recipe1M/*.parquet')

# Read and concatenate all files into a single DataFrame
df = pd.concat([pd.read_parquet(file, engine='pyarrow') for file in files], ignore_index=True)

In [7]:
df

,Name,Instructions,total_time,calories,protein,fat,sugar,ingredients,desc
0,Yogurt Parfaits,[Layer all ingredients in a serving dish.],NaN,332.06,28.30,8.76,20.82,"[{'name': 'yogurt, greek, plain, nonfat', 'qua...",
1,"Salt Free, Low Cholesterol Sugar Cookies Recipe","[Cream sugar and butter together till smooth.,...",NaN,3567.77,57.02,175.08,106.92,"[{'name': 'sugars, granulated', 'quantity': 0....",
2,Honey Sriracha Chicken Wings,"[Preheat oven to 400 degrees F., In a large bo...",50.0,3286.10,242.97,225.81,48.16,"[{'name': 'chicken, broilers or fryers, wing, ...",
3,Shrimp and Caper Salad,"[In a large bowl, toss the shrimp, green onion...",60.0,3066.25,188.09,251.61,4.95,"[{'name': 'crustaceans, shrimp, raw (not previ...",
4,Natural Peanut Butter Chocolate Bon Bons,[Measure out the cocoa powder into a mixing bo...,120.0,16252.00,271.44,272.88,3385.56,"[{'name': 'cocoa, dry powder, unsweetened', 'q...",
...,...,...,...,...,...,...,...,...,...
1080950,Soft and Chewy Chocolate Drops,[Microwave unsweetened chocolate and butter 2 ...,89.0,58706.00,131.92,6276.26,713.67,"[{'name': 'unsweetened chocolate square', 'qua...",
1080951,Zucchini Gratin With Feta,"[Preheat oven to 350, Drop zucchini slices int...",37.0,0.00,0.00,0.00,0.00,"[{'name': 'large zucchini', 'quantity': 2.0, '...",
1080952,Quick Crab Quiche,"[Sprinkle crabmeat and cheese into pie shell.,...",40.0,0.00,0.00,0.00,0.00,"[{'name': 'deep dish pie shell', 'quantity': 1...",
1080953,"Veal Piccata with Orange, Capers and Tarragon",[Season the veal with salt and pepper and coat...,1.0,6.00,0.60,0.21,0.12,"[{'name': 'veal', 'quantity': 1.0, 'unit': 'po...",
1080954,Texas Barbecue Sauce (One-Pan Wonderful),[Place all ingredients into a saucepan over me...,20.0,45778.62,125.08,2596.12,5496.86,"[{'name': 'butter', 'quantity': 14.0, 'unit': ...",

In [8]:
df.columns

Index(['Name', 'Instructions', 'total_time', 'calories', 'protein', 'fat',
       'sugar', 'ingredients', 'desc'],
      dtype='object')

In [9]:
def count_empty_ingredient(df):
    return df['ingredients'].isna().sum()

In [10]:
count_empty_ingredient(df)

0

In [11]:
def remove_duplicates_by_column(df, column):
    # Identify exact duplicate rows based on the 'name' column
    exact_duplicates = df[df.duplicated(subset=column, keep=False)]
    
    # Print the exact duplicates
    print(f"Exact duplicate rows based on {column}:")
    print(exact_duplicates)
    
    # Remove exact duplicates based on the 'name' column, keeping only the first occurrence
    filtered_df = df.drop_duplicates(subset=column, keep='first')
    
    return filtered_df

In [12]:
filtered_df_name = remove_duplicates_by_column(df, 'Name')

Exact duplicate rows based on Name:
                                                    Name  \
0                                        Yogurt Parfaits
1        Salt Free, Low Cholesterol Sugar Cookies Recipe
2                           Honey Sriracha Chicken Wings
3                                 Shrimp and Caper Salad
4               Natural Peanut Butter Chocolate Bon Bons
...                                                  ...
1080938                                  Pierogies Dough
1080939                                        Mole Pork
1080941                              Roast Turkey Breast
1080945                              Hungarian Pot Roast
1080952                                Quick Crab Quiche

                                              Instructions  total_time  \
0               [Layer all ingredients in a serving dish.]         NaN
1        [Cream sugar and butter together till smooth.,...         NaN
2        [Preheat oven to 400 degrees F., In a large bo...        50.0
3        [In a large bowl, toss the shrimp, green onion...        60.0
4        [Measure out the cocoa powder into a mixing bo...       120.0
...                                                    ...         ...
1080938  [Cut margarine into the flour, then add the eg...        30.0
1080939  [Slice Onions and Peppers., Place into a slowc...       510.0
1080941  [Set the oven at 350 degrees., If the turkey b...       200.0
1080945  [Brown all sides of roast in the oil in a dutc...       360.0
1080952  [Sprinkle crabmeat and cheese into pie shell.,...        40.0

         calories  protein      fat    sugar  \
0          332.06    28.30     8.76    20.82
1         3567.77    57.02   175.08   106.92
2         3286.10   242.97   225.81    48.16
3         3066.25   188.09   251.61     4.95
4        16252.00   271.44   272.88  3385.56
...           ...      ...      ...      ...
1080938  21150.00    36.24  2179.38   303.30
1080939     68.00     1.36     0.32    14.08
1080941      0.00     0.00     0.00     0.00
1080945   7094.00     2.98    27.23  1819.79
1080952      0.00     0.00     0.00     0.00

                                               ingredients desc
0        [{'name': 'yogurt, greek, plain, nonfat', 'qua...
1        [{'name': 'sugars, granulated', 'quantity': 0....
2        [{'name': 'chicken, broilers or fryers, wing, ...
3        [{'name': 'crustaceans, shrimp, raw (not previ...
4        [{'name': 'cocoa, dry powder, unsweetened', 'q...
...                                                    ...  ...
1080938  [{'name': 'flour', 'quantity': 6.0, 'unit': 'c...
1080939  [{'name': ' - lb pork shoulder', 'quantity': 7...
1080941  [{'name': 'boneles turkey breast half', 'quant...
1080945  [{'name': 'lb outside round roast', 'quantity'...
1080952  [{'name': 'deep dish pie shell', 'quantity': 1...

[389059 rows x 9 columns]

In [13]:
filtered_df_name

,Name,Instructions,total_time,calories,protein,fat,sugar,ingredients,desc
0,Yogurt Parfaits,[Layer all ingredients in a serving dish.],NaN,332.06,28.30,8.76,20.82,"[{'name': 'yogurt, greek, plain, nonfat', 'qua...",
1,"Salt Free, Low Cholesterol Sugar Cookies Recipe","[Cream sugar and butter together till smooth.,...",NaN,3567.77,57.02,175.08,106.92,"[{'name': 'sugars, granulated', 'quantity': 0....",
2,Honey Sriracha Chicken Wings,"[Preheat oven to 400 degrees F., In a large bo...",50.0,3286.10,242.97,225.81,48.16,"[{'name': 'chicken, broilers or fryers, wing, ...",
3,Shrimp and Caper Salad,"[In a large bowl, toss the shrimp, green onion...",60.0,3066.25,188.09,251.61,4.95,"[{'name': 'crustaceans, shrimp, raw (not previ...",
4,Natural Peanut Butter Chocolate Bon Bons,[Measure out the cocoa powder into a mixing bo...,120.0,16252.00,271.44,272.88,3385.56,"[{'name': 'cocoa, dry powder, unsweetened', 'q...",
...,...,...,...,...,...,...,...,...,...
1080949,Italian Sausage Zucchini Soup,"[Slice sausage and brown in the pot., Add cele...",30.0,32.00,1.40,0.34,2.70,"[{'name': 'sweet Italian sausage', 'quantity':...",
1080950,Soft and Chewy Chocolate Drops,[Microwave unsweetened chocolate and butter 2 ...,89.0,58706.00,131.92,6276.26,713.67,"[{'name': 'unsweetened chocolate square', 'qua...",
1080951,Zucchini Gratin With Feta,"[Preheat oven to 350, Drop zucchini slices int...",37.0,0.00,0.00,0.00,0.00,"[{'name': 'large zucchini', 'quantity': 2.0, '...",
1080953,"Veal Piccata with Orange, Capers and Tarragon",[Season the veal with salt and pepper and coat...,1.0,6.00,0.60,0.21,0.12,"[{'name': 'veal', 'quantity': 1.0, 'unit': 'po...",
1080954,Texas Barbecue Sauce (One-Pan Wonderful),[Place all ingredients into a saucepan over me...,20.0,45778.62,125.08,2596.12,5496.86,"[{'name': 'butter', 'quantity': 14.0, 'unit': ...",

In [14]:
type(filtered_df_name['Instructions'])

pandas.core.series.Series

In [15]:
filtered_df_name["Concatenated Instructions"] = filtered_df_name["Instructions"].apply(lambda x: " ".join(x))

C:\Users\burak\AppData\Local\Temp\ipykernel_18092\1574177256.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df_name["Concatenated Instructions"] = filtered_df_name["Instructions"].apply(lambda x: " ".join(x))

In [ ]:
filtered_df_name

,Name,Instructions,total_time,calories,protein,fat,sugar,ingredients,desc,Concatenated Instructions
0,Yogurt Parfaits,[Layer all ingredients in a serving dish.],NaN,332.06,28.30,8.76,20.82,"[{'name': 'yogurt, greek, plain, nonfat', 'qua...",,Layer all ingredients in a serving dish.
1,"Salt Free, Low Cholesterol Sugar Cookies Recipe","[Cream sugar and butter together till smooth.,...",NaN,3567.77,57.02,175.08,106.92,"[{'name': 'sugars, granulated', 'quantity': 0....",,Cream sugar and butter together till smooth. A...
2,Honey Sriracha Chicken Wings,"[Preheat oven to 400 degrees F., In a large bo...",50.0,3286.10,242.97,225.81,48.16,"[{'name': 'chicken, broilers or fryers, wing, ...",,Preheat oven to 400 degrees F. In a large bowl...
3,Shrimp and Caper Salad,"[In a large bowl, toss the shrimp, green onion...",60.0,3066.25,188.09,251.61,4.95,"[{'name': 'crustaceans, shrimp, raw (not previ...",,"In a large bowl, toss the shrimp, green onions..."
4,Natural Peanut Butter Chocolate Bon Bons,[Measure out the cocoa powder into a mixing bo...,120.0,16252.00,271.44,272.88,3385.56,"[{'name': 'cocoa, dry powder, unsweetened', 'q...",,Measure out the cocoa powder into a mixing bow...
...,...,...,...,...,...,...,...,...,...,...
1080949,Italian Sausage Zucchini Soup,"[Slice sausage and brown in the pot., Add cele...",30.0,32.00,1.40,0.34,2.70,"[{'name': 'sweet Italian sausage', 'quantity':...",,Slice sausage and brown in the pot. Add celery...
1080950,Soft and Chewy Chocolate Drops,[Microwave unsweetened chocolate and butter 2 ...,89.0,58706.00,131.92,6276.26,713.67,"[{'name': 'unsweetened chocolate square', 'qua...",,Microwave unsweetened chocolate and butter 2 m...
1080951,Zucchini Gratin With Feta,"[Preheat oven to 350, Drop zucchini slices int...",37.0,0.00,0.00,0.00,0.00,"[{'name': 'large zucchini', 'quantity': 2.0, '...",,Preheat oven to 350 Drop zucchini slices into ...
1080953,"Veal Piccata with Orange, Capers and Tarragon",[Season the veal with salt and pepper and coat...,1.0,6.00,0.60,0.21,0.12,"[{'name': 'veal', 'quantity': 1.0, 'unit': 'po...",,Season the veal with salt and pepper and coat ...
1080954,Texas Barbecue Sauce (One-Pan Wonderful),[Place all ingredients into a saucepan over me...,20.0,45778.62,125.08,2596.12,5496.86,"[{'name': 'butter', 'quantity': 14.0, 'unit': ...",,Place all ingredients into a saucepan over med...

In [17]:
filtered_df_all = remove_duplicates_by_column(filtered_df_name, 'Concatenated Instructions')

Exact duplicate rows based on Concatenated Instructions:
                                                   Name  \
61                      Amaretto Cranberry Juice Recipe
71                      Low Carb Seafood Cocktail Sauce
81                                          Rib Dry Rub
97                             Microwave Glazed Walnuts
110                   Red Robin Chillin' Mango Smoothie
...                                                 ...
1079902         Thick & Juicy Ultra-Saucy Cheeseburgers
1079942                         Lemon Honey Blender Pie
1079971  Shrimp Escabeche With Ginger-Grilled Pineapple
1080463                        LOUISIANA CRAWFISH CAKES
1080505                 Blackberry Vodka Collins Recipe

                                              Instructions  total_time  \
61                                          [Ice // rocks]         NaN
71                              [Stir together and serve.]         NaN
81       [Combine all ingredients in a large bowl and m...         NaN
97       [Lightly grease a baking sheet., In a 1 quart ...         2.0
110                                     [Blend and enjoy!]         NaN
...                                                    ...         ...
1079902  [Heat greased grill to medium heat., Mix first...         NaN
1079942  [Throw all ingredients in your blender and ble...         NaN
1079971  [Heat the oil in a large nonstick skillet., Se...        35.0
1080463  [Heat oil in sauce pan and sweat onions and pe...         1.0
1080505                             [Ice (shake) // rocks]         NaN

         calories  protein     fat    sugar  \
61          26.08     0.22    0.07     6.86
71         179.04     2.48    1.01    28.35
81         151.00     5.52    4.00    11.04
97       27642.00    35.64  152.60  6844.18
110       8503.21    33.88   12.10  1802.81
...           ...      ...     ...      ...
1079902      0.00     0.00    0.00     0.00
1079942   1031.00     1.02    0.00   278.39
1079971      0.00     0.00    0.00     0.00
1080463      9.99     0.00    0.00     3.00
1080505      0.00     0.00    0.00     0.00

                                               ingredients desc  \
61       [{'name': 'cranberry juice, unsweetened', 'qua...
71       [{'name': 'catsup', 'quantity': 5.0, 'unit': '...
81       [{'name': 'spices, cumin seed', 'quantity': 1....
97       [{'name': 'nuts, walnuts, english', 'quantity'...
110      [{'name': 'mango nectar, canned', 'quantity': ...
...                                                    ...  ...
1079902  [{'name': ' - lb. lean ground beef safeway  lb...
1079942  [{'name': 'white rice flour', 'quantity': 34.0...
1079971  [{'name': 'olive oil', 'quantity': 1.0, 'unit'...
1080463  [{'name': 'pommace oil', 'quantity': 1.0, 'uni...
1080505  [{'name': 'Vodka', 'quantity': 1.0, 'unit': 'o...

                                 Concatenated Instructions
61                                            Ice // rocks
71                                Stir together and serve.
81       Combine all ingredients in a large bowl and mi...
97       Lightly grease a baking sheet. In a 1 quart gl...
110                                       Blend and enjoy!
...                                                    ...
1079902  Heat greased grill to medium heat. Mix first 3...
1079942  Throw all ingredients in your blender and blen...
1079971  Heat the oil in a large nonstick skillet. Seas...
1080463  Heat oil in sauce pan and sweat onions and pep...
1080505                               Ice (shake) // rocks

[11137 rows x 10 columns]

In [18]:
filtered_df_all

,Name,Instructions,total_time,calories,protein,fat,sugar,ingredients,desc,Concatenated Instructions
0,Yogurt Parfaits,[Layer all ingredients in a serving dish.],NaN,332.06,28.30,8.76,20.82,"[{'name': 'yogurt, greek, plain, nonfat', 'qua...",,Layer all ingredients in a serving dish.
1,"Salt Free, Low Cholesterol Sugar Cookies Recipe","[Cream sugar and butter together till smooth.,...",NaN,3567.77,57.02,175.08,106.92,"[{'name': 'sugars, granulated', 'quantity': 0....",,Cream sugar and butter together till smooth. A...
2,Honey Sriracha Chicken Wings,"[Preheat oven to 400 degrees F., In a large bo...",50.0,3286.10,242.97,225.81,48.16,"[{'name': 'chicken, broilers or fryers, wing, ...",,Preheat oven to 400 degrees F. In a large bowl...
3,Shrimp and Caper Salad,"[In a large bowl, toss the shrimp, green onion...",60.0,3066.25,188.09,251.61,4.95,"[{'name': 'crustaceans, shrimp, raw (not previ...",,"In a large bowl, toss the shrimp, green onions..."
4,Natural Peanut Butter Chocolate Bon Bons,[Measure out the cocoa powder into a mixing bo...,120.0,16252.00,271.44,272.88,3385.56,"[{'name': 'cocoa, dry powder, unsweetened', 'q...",,Measure out the cocoa powder into a mixing bow...
...,...,...,...,...,...,...,...,...,...,...
1080949,Italian Sausage Zucchini Soup,"[Slice sausage and brown in the pot., Add cele...",30.0,32.00,1.40,0.34,2.70,"[{'name': 'sweet Italian sausage', 'quantity':...",,Slice sausage and brown in the pot. Add celery...
1080950,Soft and Chewy Chocolate Drops,[Microwave unsweetened chocolate and butter 2 ...,89.0,58706.00,131.92,6276.26,713.67,"[{'name': 'unsweetened chocolate square', 'qua...",,Microwave unsweetened chocolate and butter 2 m...
1080951,Zucchini Gratin With Feta,"[Preheat oven to 350, Drop zucchini slices int...",37.0,0.00,0.00,0.00,0.00,"[{'name': 'large zucchini', 'quantity': 2.0, '...",,Preheat oven to 350 Drop zucchini slices into ...
1080953,"Veal Piccata with Orange, Capers and Tarragon",[Season the veal with salt and pepper and coat...,1.0,6.00,0.60,0.21,0.12,"[{'name': 'veal', 'quantity': 1.0, 'unit': 'po...",,Season the veal with salt and pepper and coat ...
1080954,Texas Barbecue Sauce (One-Pan Wonderful),[Place all ingredients into a saucepan over me...,20.0,45778.62,125.08,2596.12,5496.86,"[{'name': 'butter', 'quantity': 14.0, 'unit': ...",,Place all ingredients into a saucepan over med...

In [19]:
filtered_df_all.to_parquet('deduplicated_recipes_recipe1M.parquet', index=False)

print("Deduplication complete! Results saved to:")
print(" - deduplicated_recipes_recipe1M.parquet (deduplicated data)")

Deduplication complete! Results saved to:
 - deduplicated_recipes_recipe1M.parquet (deduplicated data)